/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ModifyOrder struct for ModifyOrder
type ModifyOrder struct {
	AcctId string `json:"acctId,omitempty"`
	Conid int32 `json:"conid,omitempty"`
	// customer orderid
	OrderId int32 `json:"orderId,omitempty"`
	// for example LMT
	OrderType string `json:"orderType,omitempty"`
	OutsideRTH bool `json:"outsideRTH,omitempty"`
	Price float32 `json:"price,omitempty"`
	AuxPrice float32 `json:"auxPrice,omitempty"`
	// SELL or BUY
	Side string `json:"side,omitempty"`
	// optional, not required
	ListingExchange string `json:"listingExchange,omitempty"`
	Ticker string `json:"ticker,omitempty"`
	// for example DAY
	Tif string `json:"tif,omitempty"`
	// usually integer, for some special cases can be float numbers
	Quantity float32 `json:"quantity,omitempty"`
}
