/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderStatus Status of the order InvalidOrderStatus = '-1' New = '0' PartiallyFilled = '1' Filled = '2' DoneForTheDay = '3' Canceled = '4' Replaced = '5' PendingCancelReplace = '6' Stopped = '7' Rejected = '8' Suspended = '9' PendingNew = 'A' Calculated = 'B' Expired = 'C' AcceptedForBidding = 'D' PendingReplace = 'E'
type OrderStatus string

// List of orderStatus
const (
	_1 OrderStatus = "-1"
	_0 OrderStatus = "0"
	_1 OrderStatus = "1"
	_2 OrderStatus = "2"
	_3 OrderStatus = "3"
	_4 OrderStatus = "4"
	_5 OrderStatus = "5"
	_6 OrderStatus = "6"
	_7 OrderStatus = "7"
	_8 OrderStatus = "8"
	_9 OrderStatus = "9"
	A OrderStatus = "A"
	B OrderStatus = "B"
	C OrderStatus = "C"
	D OrderStatus = "D"
	E OrderStatus = "E"
)
