/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20015 struct for InlineResponse20015
type InlineResponse20015 struct {
	Amount InlineResponse20015Amount `json:"amount,omitempty"`
	Equity InlineResponse20015Equity `json:"equity,omitempty"`
	Initial InlineResponse20015Equity `json:"initial,omitempty"`
	Maintenance InlineResponse20015Equity `json:"maintenance,omitempty"`
	Warn string `json:"warn,omitempty"`
	Error string `json:"error,omitempty"`
}
