/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MarketData struct for MarketData
type MarketData struct {
	// IBKR Contract ID
	Conid float32 `json:"Conid,omitempty"`
	// Exchange
	Exchange string `json:"Exchange,omitempty"`
	MinTick float32 `json:"minTick,omitempty"`
	Last float32 `json:"Last,omitempty"`
	LastSize float32 `json:"LastSize,omitempty"`
	Bid float32 `json:"Bid,omitempty"`
	BidSize float32 `json:"BidSize,omitempty"`
	Ask float32 `json:"Ask,omitempty"`
	AskSize float32 `json:"AskSize,omitempty"`
}
