/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2006 struct for InlineResponse2006
type InlineResponse2006 struct {
	CustomerOrderId string `json:"CustomerOrderId,omitempty"`
	Symbol float32 `json:"Symbol,omitempty"`
	OrderQty float32 `json:"OrderQty,omitempty"`
	Price string `json:"Price,omitempty"`
	Side float32 `json:"Side,omitempty"`
	Status OrderStatus `json:"Status,omitempty"`
	Warning string `json:"Warning,omitempty"`
	OrderType OrderType `json:"OrderType,omitempty"`
}
