/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IbcustEntityInfoAddress struct for IbcustEntityInfoAddress
type IbcustEntityInfoAddress struct {
	Street string `json:"street,omitempty"`
	Street2 string `json:"street2,omitempty"`
	City string `json:"city,omitempty"`
	State string `json:"state,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	Country string `json:"country,omitempty"`
	CountryCode string `json:"countryCode,omitempty"`
	Compact string `json:"compact,omitempty"`
}
