/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MarketdataSnapshotBid struct for MarketdataSnapshotBid
type MarketdataSnapshotBid struct {
	Market float32 `json:"market,omitempty"`
	Price float32 `json:"price,omitempty"`
	Size float32 `json:"size,omitempty"`
}
