/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2005 struct for InlineResponse2005
type InlineResponse2005 struct {
	Ledger []InlineResponse2005Ledger `json:"Ledger,omitempty"`
	Info InlineResponse2005Info `json:"Info,omitempty"`
	Summary InlineResponse2005Summary `json:"Summary,omitempty"`
}
