/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20017 struct for InlineResponse20017
type InlineResponse20017 struct {
	ApplicantId float32 `json:"applicantId,omitempty"`
	Entities []IbcustEntityInfoEntities `json:"entities,omitempty"`
}
