/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20014 struct for InlineResponse20014
type InlineResponse20014 struct {
	ACCTID []map[string]interface{} `json:"ACCTID,omitempty"`
}
