/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountMaster struct for AccountMaster
type AccountMaster struct {
	Title string `json:"title,omitempty"`
	OfficialTitle string `json:"officialTitle,omitempty"`
}
