/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject1 struct for InlineObject1
type InlineObject1 struct {
	// The 25-character hexadecimal string that was obtained from Interactive Brokers during the OAuth consumer registration process.
	OauthConsumerKey string `json:"oauth_consumer_key,omitempty"`
	// The request token obtained from IB via /request_token.
	OauthToken string `json:"oauth_token,omitempty"`
	// The signature method used to sign the request. Currently only 'RSA-SHA256' is supported.
	OauthSignatureMethod string `json:"oauth_signature_method,omitempty"`
	// The signature for the request generated using the method specified in the oauth_signature_method parameter. See section 9 of the OAuth v1.0a specification for more details on signing requests.
	OauthSignature string `json:"oauth_signature,omitempty"`
	// Timestamp expressed in seconds since 1/1/1970 00:00:00 GMT. Must be a positive integer and greater than or equal to any timestamp used in previous requests.
	OauthTimestamp string `json:"oauth_timestamp,omitempty"`
	// A random string uniquely generated for each request.
	OauthNonce string `json:"oauth_nonce,omitempty"`
	// The verification code received from IB after the user has granted authorization.
	OauthVerifier string `json:"oauth_verifier,omitempty"`
}
