/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20021 struct for InlineResponse20021
type InlineResponse20021 struct {
	T int32 `json:"T,omitempty"`
	V int32 `json:"V,omitempty"`
}
