/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MarketdataSnapshotClosing struct for MarketdataSnapshotClosing
type MarketdataSnapshotClosing struct {
	Price float32 `json:"price,omitempty"`
}
