/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	OauthToken string `json:"oauth_token,omitempty"`
	OauthTokenSecret string `json:"oauth_token_secret,omitempty"`
}
