/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PerformanceCpsData struct for PerformanceCpsData
type PerformanceCpsData struct {
	Id string `json:"id,omitempty"`
	// for example-- acctid
	IdType string `json:"idType,omitempty"`
	// start date-- yyyyMMdd
	Start string `json:"start,omitempty"`
	BaseCurrency string `json:"baseCurrency,omitempty"`
	// each value stands for price change percent of corresponding date in dates array
	Returns []float32 `json:"returns,omitempty"`
	// end date-- yyyyMMdd
	End string `json:"end,omitempty"`
}
