/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Summary struct for Summary
type Summary struct {
	Amount float32 `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	IsNull bool `json:"isNull,omitempty"`
	Timestamp int32 `json:"timestamp,omitempty"`
	Value string `json:"value,omitempty"`
}
