/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20019 struct for InlineResponse20019
type InlineResponse20019 struct {
	Call []string `json:"call,omitempty"`
	Put []string `json:"put,omitempty"`
}
