/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20013 struct for InlineResponse20013
type InlineResponse20013 struct {
	BASE Ledger `json:"BASE,omitempty"`
}
