/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20020LocationTree struct for InlineResponse20020LocationTree
type InlineResponse20020LocationTree struct {
	DisplayName string `json:"display_name,omitempty"`
	Type string `json:"type,omitempty"`
	Locations []InlineResponse20020Locations `json:"locations,omitempty"`
}
