/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HistoryDataData struct for HistoryDataData
type HistoryDataData struct {
	// open price
	O float32 `json:"o,omitempty"`
	// close price
	C float32 `json:"c,omitempty"`
	// high price
	H float32 `json:"h,omitempty"`
	// low price
	L float32 `json:"l,omitempty"`
	// volume
	V float32 `json:"v,omitempty"`
	// unix time stamp
	T float32 `json:"t,omitempty"`
}
