/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20020 struct for InlineResponse20020
type InlineResponse20020 struct {
	// disclaimer message
	DT string `json:"DT,omitempty"`
	// fyi code
	FC string `json:"FC,omitempty"`
}
