/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	Orders []Order `json:"orders,omitempty"`
	Notifications []map[string]interface{} `json:"notifications,omitempty"`
}
