/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SummaryTotal struct for SummaryTotal
type SummaryTotal struct {
	// total change amount
	Chg string `json:"chg,omitempty"`
	// change percent
	Rtn string `json:"rtn,omitempty"`
	// set to true if any external account data is not available for starting or ending date, resulting in potentially unusual total values.
	IncompleteData bool `json:"incompleteData,omitempty"`
	EndVal string `json:"endVal,omitempty"`
	StartVal string `json:"startVal,omitempty"`
}
