/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse4001 struct for InlineResponse4001
type InlineResponse4001 struct {
	Error string `json:"error,omitempty"`
	StatusCode int32 `json:"statusCode,omitempty"`
}
