/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2005Amount struct for InlineResponse2005Amount
type InlineResponse2005Amount struct {
	// for example 23,000 USD
	Amount string `json:"amount,omitempty"`
	// for example 1.1 ... 1.2 USD
	Commission string `json:"commission,omitempty"`
	Total string `json:"total,omitempty"`
}
