/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20011 struct for InlineResponse20011
type InlineResponse20011 struct {
	ConId float32 `json:"ConId,omitempty"`
	Complete bool `json:"Complete,omitempty"`
	Mapping []MarketdataExchangeComponentsMapping `json:"mapping,omitempty"`
}
