/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SummaryBalanceByDateSeries struct for SummaryBalanceByDateSeries
type SummaryBalanceByDateSeries struct {
	Id string `json:"id,omitempty"`
	GroupId string `json:"groupId,omitempty"`
	Name string `json:"name,omitempty"`
	Date [][]float32 `json:"date,omitempty"`
}
