/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20016 struct for InlineResponse20016
type InlineResponse20016 struct {
	Symbol []map[string]interface{} `json:"symbol,omitempty"`
}
