/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StatsData struct for StatsData
type StatsData struct {
	Conid float32 `json:"Conid,omitempty"`
	Exchange string `json:"Exchange,omitempty"`
	V float32 `json:"V,omitempty"`
	T float32 `json:"T,omitempty"`
	TT float32 `json:"TT,omitempty"`
	// Object, payload depends on event type. See confluence page for IGEvntUpd.
	P string `json:"P,omitempty"`
}
