/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// StocksContracts struct for StocksContracts
type StocksContracts struct {
	// conid of the stock contract
	Conid int32 `json:"conid,omitempty"`
	Exchange string `json:"exchange,omitempty"`
}
