/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	DiffieHellmanResponse string `json:"diffie_hellman_response,omitempty"`
	LiveSessionTokenSignature string `json:"live_session_token_signature,omitempty"`
}
