/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20020FilterList struct for InlineResponse20020FilterList
type InlineResponse20020FilterList struct {
	Group string `json:"group,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Code string `json:"code,omitempty"`
	Type string `json:"type,omitempty"`
}
