/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20010 struct for InlineResponse20010
type InlineResponse20010 struct {
	Conid string `json:"Conid,omitempty"`
	// 0 = Real time data 1 = Delayed data 
	Temporality float32 `json:"Temporality,omitempty"`
	Complete bool `json:"Complete,omitempty"`
	Trade MarketdataSnapshotTrade `json:"Trade,omitempty"`
	Closing MarketdataSnapshotClosing `json:"Closing,omitempty"`
	Bid MarketdataSnapshotBid `json:"Bid,omitempty"`
	Offer MarketdataSnapshotBid `json:"Offer,omitempty"`
}
