/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20020ScanTypeList struct for InlineResponse20020ScanTypeList
type InlineResponse20020ScanTypeList struct {
	DisplayName string `json:"display_name,omitempty"`
	Code string `json:"code,omitempty"`
	Instruments []string `json:"instruments,omitempty"`
}
