/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	Set bool `json:"set,omitempty"`
	AcctId string `json:"acctId,omitempty"`
}
