/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Contract Contains all details of the contract, including rules you can use when placing orders
type Contract struct {
	// true means you can trade outside RTH(regular trading hours)
	RTH bool `json:"r_t_h,omitempty"`
	// same as that in request
	ConId string `json:"con_id,omitempty"`
	CompanyName string `json:"company_name,omitempty"`
	Exchange string `json:"exchange,omitempty"`
	// for exmple FB
	LocalSymbol string `json:"local_symbol,omitempty"`
	// for example STK
	InstrumentType string `json:"instrument_type,omitempty"`
	Currency string `json:"currency,omitempty"`
	CompanyName string `json:"companyName,omitempty"`
	Category string `json:"category,omitempty"`
	Industry string `json:"industry,omitempty"`
	Rules ContractRules `json:"rules,omitempty"`
}
