/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2009InstrumentList struct for InlineResponse2009InstrumentList
type InlineResponse2009InstrumentList struct {
	DisplayName string `json:"display_name,omitempty"`
	Type string `json:"type,omitempty"`
	Filters []string `json:"filters,omitempty"`
}
