/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ScannerParamsFilter struct for ScannerParamsFilter
type ScannerParamsFilter struct {
	Code string `json:"code,omitempty"`
	Value float32 `json:"value,omitempty"`
}
