/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20019 struct for InlineResponse20019
type InlineResponse20019 struct {
	// optional, if A doesn't exist, it means user can't toggle this option. 0-off, 1-on.
	A int32 `json:"A,omitempty"`
	// fyi code
	FC string `json:"FC,omitempty"`
	// disclaimer read, 1 = yes, = 0 no.
	H int32 `json:"H,omitempty"`
	// detailed description
	FD string `json:"FD,omitempty"`
	// title
	FN string `json:"FN,omitempty"`
}
