/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IbcustEntityInfoEntities struct for IbcustEntityInfoEntities
type IbcustEntityInfoEntities struct {
	CanTrade bool `json:"canTrade,omitempty"`
	CanSign bool `json:"canSign,omitempty"`
	Type string `json:"type,omitempty"`
	Name IbcustEntityInfoName `json:"name,omitempty"`
	Address IbcustEntityInfoAddress `json:"address,omitempty"`
	IdentDocs []map[string]interface{} `json:"identDocs,omitempty"`
}
