/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20018 struct for InlineResponse20018
type InlineResponse20018 struct {
	// unread number
	BN int32 `json:"BN,omitempty"`
}
