/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2005Info struct for InlineResponse2005Info
type InlineResponse2005Info struct {
	AccountType string `json:"AccountType,omitempty"`
	AccountCode string `json:"AccountCode,omitempty"`
	AccountReady string `json:"AccountReady,omitempty"`
	Cushion string `json:"Cushion,omitempty"`
	DayTradesRemaining string `json:"DayTradesRemaining,omitempty"`
	DayTradesRemainingT string `json:"DayTradesRemainingT,omitempty"`
	DayTradesRemainingT2 string `json:"DayTradesRemainingT+2,omitempty"`
	DayTradesRemainingT3 string `json:"DayTradesRemainingT+3,omitempty"`
	DayTradesRemainingT4 string `json:"DayTradesRemainingT+4,omitempty"`
	HighestSeverity string `json:"HighestSeverity,omitempty"`
	LeverageS string `json:"Leverage-S,omitempty"`
	LookAheadNextChange string `json:"LookAheadNextChange,omitempty"`
	SegmentTitleC string `json:"SegmentTitle-C,omitempty"`
	SegmentTitleS string `json:"SegmentTitle-S,omitempty"`
	TradingTypeS string `json:"TradingType-S,omitempty"`
	WhatIfPMEnabled string `json:"WhatIfPMEnabled,omitempty"`
}
