/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2009 struct for InlineResponse2009
type InlineResponse2009 struct {
	ContractId float32 `json:"ContractId,omitempty"`
	Ticker string `json:"Ticker,omitempty"`
	SecurityType string `json:"SecurityType,omitempty"`
	Exchange string `json:"Exchange,omitempty"`
	CompanyName string `json:"CompanyName,omitempty"`
	Currency string `json:"Currency,omitempty"`
}
