/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20020Locations struct for InlineResponse20020Locations
type InlineResponse20020Locations struct {
	DisplayName string `json:"display_name,omitempty"`
	Type string `json:"type,omitempty"`
}
