/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Performance struct for Performance
type Performance struct {
	Id string `json:"id,omitempty"`
	Cps PerformanceCps `json:"cps,omitempty"`
	Tpps PerformanceTpps `json:"tpps,omitempty"`
	Nav PerformanceNav `json:"nav,omitempty"`
	Pm string `json:"pm,omitempty"`
	Included []string `json:"included,omitempty"`
	CurrencyType string `json:"currencyType,omitempty"`
	Rc int32 `json:"rc,omitempty"`
}
