/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2008 struct for InlineResponse2008
type InlineResponse2008 struct {
	Conid int32 `json:"conid,omitempty"`
	CompanyHeader string `json:"companyHeader,omitempty"`
	CompanyName string `json:"companyName,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Description string `json:"description,omitempty"`
	Opt string `json:"opt,omitempty"`
	War string `json:"war,omitempty"`
	Sections []map[string]interface{} `json:"sections,omitempty"`
}
