/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// HistoryData struct for HistoryData
type HistoryData struct {
	// start date time
	Start string `json:"start,omitempty"`
	// Market Data Availability. The field may contain two chars. The first char is the primary code: R = Realtime, D = Delayed, Z = Frozen, Y = Frozen Delayed. The second char is the secondary code: P = Snapshot Available, p = Consolidated. 
	MdAvailability string `json:"mdAvailability,omitempty"`
	BarLength int32 `json:"barLength,omitempty"`
	Delay int32 `json:"delay,omitempty"`
	// High value during this time series with format %h/%v/%t. %h is the high price (scaled by priceFactor), %v is volume (volume factor will always be 100 (reported volume = actual volume/100)) and %t is minutes from start time of the chart 
	High string `json:"high,omitempty"`
	// Low value during this time series with format %l/%v/%t. %l is the low price (scaled by priceFactor), %v is volume (volume factor will always be 100 (reported volume = actual volume/100)) and %t is minutes from start time of the chart 
	Low string `json:"low,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Text string `json:"text,omitempty"`
	TickNum string `json:"tickNum,omitempty"`
	TimePeriod string `json:"timePeriod,omitempty"`
	// priceFactor is price increment obtained from display rule
	PriceFactor int32 `json:"priceFactor,omitempty"`
	Data []HistoryDataData `json:"data,omitempty"`
	// total number of points
	Points float32 `json:"points,omitempty"`
	TravelTime float32 `json:"travelTime,omitempty"`
}
