/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2009 struct for InlineResponse2009
type InlineResponse2009 struct {
	ScanTypeList []InlineResponse2009ScanTypeList `json:"scan_type_list,omitempty"`
	InstrumentList []InlineResponse2009InstrumentList `json:"instrument_list,omitempty"`
	FilterList []InlineResponse2009FilterList `json:"filter_list,omitempty"`
	LocationTree []InlineResponse2009LocationTree `json:"location_tree,omitempty"`
}
