/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CalendarRequestFilters struct for CalendarRequestFilters
type CalendarRequestFilters struct {
	// value can be 'true' or 'false'.
	RecentlyHeld string `json:"recently_held,omitempty"`
	// value can be 'true' or 'false'.
	CorporateEarnings string `json:"corporate_earnings,omitempty"`
	// value can be 'true' or 'false'.
	DivExDates string `json:"DivExDates,omitempty"`
	// value can be 'true' or 'false'.
	Ipo string `json:"ipo,omitempty"`
	// value can be 'true' or 'false'.
	Splits string `json:"splits,omitempty"`
	// value can be 'true' or 'false'.
	CorporateEvents string `json:"corporate_events,omitempty"`
	// value can be 'true' or 'false'.
	EconomicEvents string `json:"economic_events,omitempty"`
	// value can be 'true' or 'false'.
	OptionShowMonthly string `json:"option_show_monthly,omitempty"`
	// value can be 'true' or 'false'.
	OptionShowWeekly string `json:"option_show_weekly,omitempty"`
	// default is 'All'.
	Country string `json:"country,omitempty"`
	// default is '250'.
	Limit string `json:"limit,omitempty"`
	// default is '50'.
	LimitRegion string `json:"limit_region,omitempty"`
}
