/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CalendarRequestDate struct for CalendarRequestDate
type CalendarRequestDate struct {
	// start date of a period. for example 20180808-0400
	Start string `json:"start,omitempty"`
	// end date of a period. for example 20180808-0400
	End string `json:"end,omitempty"`
}
