/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CalendarRequest struct for CalendarRequest
type CalendarRequest struct {
	Date CalendarRequestDate `json:"date,omitempty"`
	Filters CalendarRequestFilters `json:"filters,omitempty"`
}
