/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Stocks This is an object of object(s), with the symbol(for example, FB) as key and contract details as the object 
type Stocks struct {
	// company name
	Name string `json:"name,omitempty"`
	// company name in Chinese
	ChineseName string `json:"chineseName,omitempty"`
	AssetClass string `json:"assetClass,omitempty"`
	// array of contracts from different exchanges
	Contracts []StocksContracts `json:"contracts,omitempty"`
}
