/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2004 struct for InlineResponse2004
type InlineResponse2004 struct {
	Position float32 `json:"Position,omitempty"`
	AverageCost float32 `json:"AverageCost,omitempty"`
	ContractId float32 `json:"ContractId,omitempty"`
}
