/*
 * IBKR 3rd Party Web API
 *
 * Interactive Brokers Web API for 3rd Party Companies
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderState An object containing all the properties defining an order
type OrderState struct {
	CustomerOrderId float32 `json:"CustomerOrderId,omitempty"`
	ContractId float32 `json:"ContractId,omitempty"`
	Ticker string `json:"Ticker,omitempty"`
	ListingExchange string `json:"ListingExchange,omitempty"`
	RemainingQuantity float32 `json:"RemainingQuantity,omitempty"`
	FilledQuantity float32 `json:"FilledQuantity,omitempty"`
	OrderType OrderType `json:"OrderType,omitempty"`
	TimeInForce TimeInForce `json:"TimeInForce,omitempty"`
	OutsideRTH string `json:"OutsideRTH,omitempty"`
	Side string `json:"Side,omitempty"`
	Price float32 `json:"Price,omitempty"`
	Status OrderStatus `json:"Status,omitempty"`
	Warning string `json:"Warning,omitempty"`
	TransactionTime string `json:"TransactionTime,omitempty"`
}
