/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse2009LocationTree struct for InlineResponse2009LocationTree
type InlineResponse2009LocationTree struct {
	DisplayName string `json:"display_name,omitempty"`
	Type string `json:"type,omitempty"`
	Locations []InlineResponse2009Locations `json:"locations,omitempty"`
}
