/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	AcctIds []string `json:"acctIds,omitempty"`
}
