/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Account account information
type Account struct {
	Id string `json:"id,omitempty"`
	AccountId string `json:"accountId,omitempty"`
	AccountVan string `json:"accountVan,omitempty"`
	AccountTitle string `json:"accountTitle,omitempty"`
	DisplayName string `json:"displayName,omitempty"`
	AccountAlias string `json:"accountAlias,omitempty"`
	AccountStatus float32 `json:"accountStatus,omitempty"`
	Currency string `json:"currency,omitempty"`
	Type string `json:"type,omitempty"`
	TradingType string `json:"tradingType,omitempty"`
	Faclient bool `json:"faclient,omitempty"`
	Parent string `json:"parent,omitempty"`
	Desc string `json:"desc,omitempty"`
	Covestor bool `json:"covestor,omitempty"`
	Master AccountMaster `json:"master,omitempty"`
}
