/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Trade struct for Trade
type Trade struct {
	ExecutionId string `json:"execution_id,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Side string `json:"side,omitempty"`
	OrderDescription string `json:"order_description,omitempty"`
	TradeTime string `json:"trade_time,omitempty"`
	TradeTimeR float32 `json:"trade_time_r,omitempty"`
	Size string `json:"size,omitempty"`
	Price string `json:"price,omitempty"`
	Submitter string `json:"submitter,omitempty"`
	Exchange string `json:"exchange,omitempty"`
	Comission float32 `json:"comission,omitempty"`
	NetAmount float32 `json:"net_amount,omitempty"`
	Account string `json:"account,omitempty"`
	CompanyName string `json:"company_name,omitempty"`
	ContractDescription1 string `json:"contract_description_1,omitempty"`
	SecType string `json:"sec_type,omitempty"`
	Conidex string `json:"conidex,omitempty"`
	Position string `json:"position,omitempty"`
	ClearingId string `json:"clearing_id,omitempty"`
	ClearingName string `json:"clearing_name,omitempty"`
}
