/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SummaryExcludedAccounts struct for SummaryExcludedAccounts
type SummaryExcludedAccounts struct {
	LastUpdateAttempt string `json:"lastUpdateAttempt,omitempty"`
	FiName string `json:"fiName,omitempty"`
	AcctTitle string `json:"acctTitle,omitempty"`
	AcctNumAtFI string `json:"acctNumAtFI,omitempty"`
	AcctId string `json:"acctId,omitempty"`
	LastUpdate string `json:"lastUpdate,omitempty"`
	HarvestCode int32 `json:"harvestCode,omitempty"`
	LastUpdateStatusCode string `json:"lastUpdateStatusCode,omitempty"`
	Rc int32 `json:"rc,omitempty"`
}
