/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20022 struct for InlineResponse20022
type InlineResponse20022 struct {
	AcctId map[string]interface{} `json:"acctId,omitempty"`
}
