/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse20016 struct for InlineResponse20016
type InlineResponse20016 struct {
	OrderId string `json:"order_id,omitempty"`
	LocalOrderId string `json:"local_order_id,omitempty"`
	OrderStatus string `json:"order_status,omitempty"`
}
