/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SetAccount struct for SetAccount
type SetAccount struct {
	// Account ID
	AcctId string `json:"acctId,omitempty"`
}
