/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20017 struct for InlineResponse20017
type InlineResponse20017 struct {
	ServerId *string `json:"server_id,omitempty"`
	Conid *int32 `json:"conid,omitempty"`
	Updated *int32 `json:"_updated,omitempty"`
	// Last Price
	Var31 *string `json:"31,omitempty"`
	// Symbol
	Var55 *string `json:"55,omitempty"`
	// Text
	Var58 *string `json:"58,omitempty"`
	// High
	Var70 *string `json:"70,omitempty"`
	// Low
	Var71 *string `json:"71,omitempty"`
	// Position
	Var72 *string `json:"72,omitempty"`
	// Market Value
	Var73 *string `json:"73,omitempty"`
	// Average Price
	Var74 *string `json:"74,omitempty"`
	// Unrealized PnL
	Var75 *string `json:"75,omitempty"`
	// Formatted position
	Var76 *string `json:"76,omitempty"`
	// Formatted Unrealized PnL
	Var77 *string `json:"77,omitempty"`
	// Daily PnL
	Var78 *string `json:"78,omitempty"`
	// Change Price
	Var82 *string `json:"82,omitempty"`
	// Change Percent
	Var83 *string `json:"83,omitempty"`
	// Bid Price
	Var84 *string `json:"84,omitempty"`
	// Ask Size
	Var85 *string `json:"85,omitempty"`
	// Ask Price
	Var86 *string `json:"86,omitempty"`
	// Volume
	Var87 *string `json:"87,omitempty"`
	// Bid Size
	Var88 *string `json:"88,omitempty"`
	// Exchange
	Var6004 *string `json:"6004,omitempty"`
	// Conid
	Var6008 *string `json:"6008,omitempty"`
	// Security Type
	Var6070 *string `json:"6070,omitempty"`
	// Months
	Var6072 *string `json:"6072,omitempty"`
	// Regular Expiry
	Var6073 *string `json:"6073,omitempty"`
	// Marker for market data delivery method (similar to request id)
	Var6119 *string `json:"6119,omitempty"`
	// Underlying Conid. Use /trsrv/secdef to get more information about the security
	Var6457 *string `json:"6457,omitempty"`
	// Market Data Availability. The field may contain two chars. The first char is the primary code: R = Realtime, D = Delayed, Z = Frozen, Y = Frozen Delayed. The second char is the secondary code: P = Snapshot Available, p = Consolidated. 
	Var6509 *string `json:"6509,omitempty"`
	// Company name
	Var7051 *string `json:"7051,omitempty"`
	// Conid + Exchange
	Var7094 *string `json:"7094,omitempty"`
	// Contract Description
	Var7219 *string `json:"7219,omitempty"`
	// Contract Description
	Var7220 *string `json:"7220,omitempty"`
	// Listing Exchange
	Var7221 *string `json:"7221,omitempty"`
	// Industry
	Var7280 *string `json:"7280,omitempty"`
	// Category
	Var7281 *string `json:"7281,omitempty"`
	// Average Daily Volume
	Var7282 *string `json:"7282,omitempty"`
	// Implied volatility of the option
	Var7633 *string `json:"7633,omitempty"`
	// Historic Volume (30d)
	Var7284 *string `json:"7284,omitempty"`
	// Put/Call Ratio
	Var7285 *string `json:"7285,omitempty"`
	// Dividend Amount
	Var7286 *string `json:"7286,omitempty"`
	// Dividend Yield %
	Var7287 *string `json:"7287,omitempty"`
	// Ex-date of the dividend
	Var7288 *string `json:"7288,omitempty"`
	// Market Cap
	Var7289 *string `json:"7289,omitempty"`
	// P/E
	Var7290 *string `json:"7290,omitempty"`
	// EPS
	Var7291 *string `json:"7291,omitempty"`
	// Cost Basis
	Var7292 *string `json:"7292,omitempty"`
	// 52 Week High
	Var7293 *string `json:"7293,omitempty"`
	// 52 Week Low
	Var7294 *string `json:"7294,omitempty"`
	// Open Price
	Var7295 *string `json:"7295,omitempty"`
	// Close Price
	Var7296 *string `json:"7296,omitempty"`
}

// NewInlineResponse20017 instantiates a new InlineResponse20017 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20017() *InlineResponse20017 {
	this := InlineResponse20017{}
	return &this
}

// NewInlineResponse20017WithDefaults instantiates a new InlineResponse20017 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20017WithDefaults() *InlineResponse20017 {
	this := InlineResponse20017{}
	return &this
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *InlineResponse20017) GetServerId() string {
	if o == nil || o.ServerId == nil {
		var ret string
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetServerIdOk() (*string, bool) {
	if o == nil || o.ServerId == nil {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *InlineResponse20017) HasServerId() bool {
	if o != nil && o.ServerId != nil {
		return true
	}

	return false
}

// SetServerId gets a reference to the given string and assigns it to the ServerId field.
func (o *InlineResponse20017) SetServerId(v string) {
	o.ServerId = &v
}

// GetConid returns the Conid field value if set, zero value otherwise.
func (o *InlineResponse20017) GetConid() int32 {
	if o == nil || o.Conid == nil {
		var ret int32
		return ret
	}
	return *o.Conid
}

// GetConidOk returns a tuple with the Conid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetConidOk() (*int32, bool) {
	if o == nil || o.Conid == nil {
		return nil, false
	}
	return o.Conid, true
}

// HasConid returns a boolean if a field has been set.
func (o *InlineResponse20017) HasConid() bool {
	if o != nil && o.Conid != nil {
		return true
	}

	return false
}

// SetConid gets a reference to the given int32 and assigns it to the Conid field.
func (o *InlineResponse20017) SetConid(v int32) {
	o.Conid = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *InlineResponse20017) GetUpdated() int32 {
	if o == nil || o.Updated == nil {
		var ret int32
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetUpdatedOk() (*int32, bool) {
	if o == nil || o.Updated == nil {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *InlineResponse20017) HasUpdated() bool {
	if o != nil && o.Updated != nil {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given int32 and assigns it to the Updated field.
func (o *InlineResponse20017) SetUpdated(v int32) {
	o.Updated = &v
}

// GetVar31 returns the Var31 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar31() string {
	if o == nil || o.Var31 == nil {
		var ret string
		return ret
	}
	return *o.Var31
}

// GetVar31Ok returns a tuple with the Var31 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar31Ok() (*string, bool) {
	if o == nil || o.Var31 == nil {
		return nil, false
	}
	return o.Var31, true
}

// HasVar31 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar31() bool {
	if o != nil && o.Var31 != nil {
		return true
	}

	return false
}

// SetVar31 gets a reference to the given string and assigns it to the Var31 field.
func (o *InlineResponse20017) SetVar31(v string) {
	o.Var31 = &v
}

// GetVar55 returns the Var55 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar55() string {
	if o == nil || o.Var55 == nil {
		var ret string
		return ret
	}
	return *o.Var55
}

// GetVar55Ok returns a tuple with the Var55 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar55Ok() (*string, bool) {
	if o == nil || o.Var55 == nil {
		return nil, false
	}
	return o.Var55, true
}

// HasVar55 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar55() bool {
	if o != nil && o.Var55 != nil {
		return true
	}

	return false
}

// SetVar55 gets a reference to the given string and assigns it to the Var55 field.
func (o *InlineResponse20017) SetVar55(v string) {
	o.Var55 = &v
}

// GetVar58 returns the Var58 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar58() string {
	if o == nil || o.Var58 == nil {
		var ret string
		return ret
	}
	return *o.Var58
}

// GetVar58Ok returns a tuple with the Var58 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar58Ok() (*string, bool) {
	if o == nil || o.Var58 == nil {
		return nil, false
	}
	return o.Var58, true
}

// HasVar58 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar58() bool {
	if o != nil && o.Var58 != nil {
		return true
	}

	return false
}

// SetVar58 gets a reference to the given string and assigns it to the Var58 field.
func (o *InlineResponse20017) SetVar58(v string) {
	o.Var58 = &v
}

// GetVar70 returns the Var70 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar70() string {
	if o == nil || o.Var70 == nil {
		var ret string
		return ret
	}
	return *o.Var70
}

// GetVar70Ok returns a tuple with the Var70 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar70Ok() (*string, bool) {
	if o == nil || o.Var70 == nil {
		return nil, false
	}
	return o.Var70, true
}

// HasVar70 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar70() bool {
	if o != nil && o.Var70 != nil {
		return true
	}

	return false
}

// SetVar70 gets a reference to the given string and assigns it to the Var70 field.
func (o *InlineResponse20017) SetVar70(v string) {
	o.Var70 = &v
}

// GetVar71 returns the Var71 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar71() string {
	if o == nil || o.Var71 == nil {
		var ret string
		return ret
	}
	return *o.Var71
}

// GetVar71Ok returns a tuple with the Var71 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar71Ok() (*string, bool) {
	if o == nil || o.Var71 == nil {
		return nil, false
	}
	return o.Var71, true
}

// HasVar71 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar71() bool {
	if o != nil && o.Var71 != nil {
		return true
	}

	return false
}

// SetVar71 gets a reference to the given string and assigns it to the Var71 field.
func (o *InlineResponse20017) SetVar71(v string) {
	o.Var71 = &v
}

// GetVar72 returns the Var72 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar72() string {
	if o == nil || o.Var72 == nil {
		var ret string
		return ret
	}
	return *o.Var72
}

// GetVar72Ok returns a tuple with the Var72 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar72Ok() (*string, bool) {
	if o == nil || o.Var72 == nil {
		return nil, false
	}
	return o.Var72, true
}

// HasVar72 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar72() bool {
	if o != nil && o.Var72 != nil {
		return true
	}

	return false
}

// SetVar72 gets a reference to the given string and assigns it to the Var72 field.
func (o *InlineResponse20017) SetVar72(v string) {
	o.Var72 = &v
}

// GetVar73 returns the Var73 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar73() string {
	if o == nil || o.Var73 == nil {
		var ret string
		return ret
	}
	return *o.Var73
}

// GetVar73Ok returns a tuple with the Var73 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar73Ok() (*string, bool) {
	if o == nil || o.Var73 == nil {
		return nil, false
	}
	return o.Var73, true
}

// HasVar73 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar73() bool {
	if o != nil && o.Var73 != nil {
		return true
	}

	return false
}

// SetVar73 gets a reference to the given string and assigns it to the Var73 field.
func (o *InlineResponse20017) SetVar73(v string) {
	o.Var73 = &v
}

// GetVar74 returns the Var74 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar74() string {
	if o == nil || o.Var74 == nil {
		var ret string
		return ret
	}
	return *o.Var74
}

// GetVar74Ok returns a tuple with the Var74 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar74Ok() (*string, bool) {
	if o == nil || o.Var74 == nil {
		return nil, false
	}
	return o.Var74, true
}

// HasVar74 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar74() bool {
	if o != nil && o.Var74 != nil {
		return true
	}

	return false
}

// SetVar74 gets a reference to the given string and assigns it to the Var74 field.
func (o *InlineResponse20017) SetVar74(v string) {
	o.Var74 = &v
}

// GetVar75 returns the Var75 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar75() string {
	if o == nil || o.Var75 == nil {
		var ret string
		return ret
	}
	return *o.Var75
}

// GetVar75Ok returns a tuple with the Var75 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar75Ok() (*string, bool) {
	if o == nil || o.Var75 == nil {
		return nil, false
	}
	return o.Var75, true
}

// HasVar75 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar75() bool {
	if o != nil && o.Var75 != nil {
		return true
	}

	return false
}

// SetVar75 gets a reference to the given string and assigns it to the Var75 field.
func (o *InlineResponse20017) SetVar75(v string) {
	o.Var75 = &v
}

// GetVar76 returns the Var76 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar76() string {
	if o == nil || o.Var76 == nil {
		var ret string
		return ret
	}
	return *o.Var76
}

// GetVar76Ok returns a tuple with the Var76 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar76Ok() (*string, bool) {
	if o == nil || o.Var76 == nil {
		return nil, false
	}
	return o.Var76, true
}

// HasVar76 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar76() bool {
	if o != nil && o.Var76 != nil {
		return true
	}

	return false
}

// SetVar76 gets a reference to the given string and assigns it to the Var76 field.
func (o *InlineResponse20017) SetVar76(v string) {
	o.Var76 = &v
}

// GetVar77 returns the Var77 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar77() string {
	if o == nil || o.Var77 == nil {
		var ret string
		return ret
	}
	return *o.Var77
}

// GetVar77Ok returns a tuple with the Var77 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar77Ok() (*string, bool) {
	if o == nil || o.Var77 == nil {
		return nil, false
	}
	return o.Var77, true
}

// HasVar77 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar77() bool {
	if o != nil && o.Var77 != nil {
		return true
	}

	return false
}

// SetVar77 gets a reference to the given string and assigns it to the Var77 field.
func (o *InlineResponse20017) SetVar77(v string) {
	o.Var77 = &v
}

// GetVar78 returns the Var78 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar78() string {
	if o == nil || o.Var78 == nil {
		var ret string
		return ret
	}
	return *o.Var78
}

// GetVar78Ok returns a tuple with the Var78 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar78Ok() (*string, bool) {
	if o == nil || o.Var78 == nil {
		return nil, false
	}
	return o.Var78, true
}

// HasVar78 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar78() bool {
	if o != nil && o.Var78 != nil {
		return true
	}

	return false
}

// SetVar78 gets a reference to the given string and assigns it to the Var78 field.
func (o *InlineResponse20017) SetVar78(v string) {
	o.Var78 = &v
}

// GetVar82 returns the Var82 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar82() string {
	if o == nil || o.Var82 == nil {
		var ret string
		return ret
	}
	return *o.Var82
}

// GetVar82Ok returns a tuple with the Var82 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar82Ok() (*string, bool) {
	if o == nil || o.Var82 == nil {
		return nil, false
	}
	return o.Var82, true
}

// HasVar82 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar82() bool {
	if o != nil && o.Var82 != nil {
		return true
	}

	return false
}

// SetVar82 gets a reference to the given string and assigns it to the Var82 field.
func (o *InlineResponse20017) SetVar82(v string) {
	o.Var82 = &v
}

// GetVar83 returns the Var83 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar83() string {
	if o == nil || o.Var83 == nil {
		var ret string
		return ret
	}
	return *o.Var83
}

// GetVar83Ok returns a tuple with the Var83 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar83Ok() (*string, bool) {
	if o == nil || o.Var83 == nil {
		return nil, false
	}
	return o.Var83, true
}

// HasVar83 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar83() bool {
	if o != nil && o.Var83 != nil {
		return true
	}

	return false
}

// SetVar83 gets a reference to the given string and assigns it to the Var83 field.
func (o *InlineResponse20017) SetVar83(v string) {
	o.Var83 = &v
}

// GetVar84 returns the Var84 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar84() string {
	if o == nil || o.Var84 == nil {
		var ret string
		return ret
	}
	return *o.Var84
}

// GetVar84Ok returns a tuple with the Var84 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar84Ok() (*string, bool) {
	if o == nil || o.Var84 == nil {
		return nil, false
	}
	return o.Var84, true
}

// HasVar84 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar84() bool {
	if o != nil && o.Var84 != nil {
		return true
	}

	return false
}

// SetVar84 gets a reference to the given string and assigns it to the Var84 field.
func (o *InlineResponse20017) SetVar84(v string) {
	o.Var84 = &v
}

// GetVar85 returns the Var85 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar85() string {
	if o == nil || o.Var85 == nil {
		var ret string
		return ret
	}
	return *o.Var85
}

// GetVar85Ok returns a tuple with the Var85 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar85Ok() (*string, bool) {
	if o == nil || o.Var85 == nil {
		return nil, false
	}
	return o.Var85, true
}

// HasVar85 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar85() bool {
	if o != nil && o.Var85 != nil {
		return true
	}

	return false
}

// SetVar85 gets a reference to the given string and assigns it to the Var85 field.
func (o *InlineResponse20017) SetVar85(v string) {
	o.Var85 = &v
}

// GetVar86 returns the Var86 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar86() string {
	if o == nil || o.Var86 == nil {
		var ret string
		return ret
	}
	return *o.Var86
}

// GetVar86Ok returns a tuple with the Var86 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar86Ok() (*string, bool) {
	if o == nil || o.Var86 == nil {
		return nil, false
	}
	return o.Var86, true
}

// HasVar86 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar86() bool {
	if o != nil && o.Var86 != nil {
		return true
	}

	return false
}

// SetVar86 gets a reference to the given string and assigns it to the Var86 field.
func (o *InlineResponse20017) SetVar86(v string) {
	o.Var86 = &v
}

// GetVar87 returns the Var87 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar87() string {
	if o == nil || o.Var87 == nil {
		var ret string
		return ret
	}
	return *o.Var87
}

// GetVar87Ok returns a tuple with the Var87 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar87Ok() (*string, bool) {
	if o == nil || o.Var87 == nil {
		return nil, false
	}
	return o.Var87, true
}

// HasVar87 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar87() bool {
	if o != nil && o.Var87 != nil {
		return true
	}

	return false
}

// SetVar87 gets a reference to the given string and assigns it to the Var87 field.
func (o *InlineResponse20017) SetVar87(v string) {
	o.Var87 = &v
}

// GetVar88 returns the Var88 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar88() string {
	if o == nil || o.Var88 == nil {
		var ret string
		return ret
	}
	return *o.Var88
}

// GetVar88Ok returns a tuple with the Var88 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar88Ok() (*string, bool) {
	if o == nil || o.Var88 == nil {
		return nil, false
	}
	return o.Var88, true
}

// HasVar88 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar88() bool {
	if o != nil && o.Var88 != nil {
		return true
	}

	return false
}

// SetVar88 gets a reference to the given string and assigns it to the Var88 field.
func (o *InlineResponse20017) SetVar88(v string) {
	o.Var88 = &v
}

// GetVar6004 returns the Var6004 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6004() string {
	if o == nil || o.Var6004 == nil {
		var ret string
		return ret
	}
	return *o.Var6004
}

// GetVar6004Ok returns a tuple with the Var6004 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6004Ok() (*string, bool) {
	if o == nil || o.Var6004 == nil {
		return nil, false
	}
	return o.Var6004, true
}

// HasVar6004 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6004() bool {
	if o != nil && o.Var6004 != nil {
		return true
	}

	return false
}

// SetVar6004 gets a reference to the given string and assigns it to the Var6004 field.
func (o *InlineResponse20017) SetVar6004(v string) {
	o.Var6004 = &v
}

// GetVar6008 returns the Var6008 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6008() string {
	if o == nil || o.Var6008 == nil {
		var ret string
		return ret
	}
	return *o.Var6008
}

// GetVar6008Ok returns a tuple with the Var6008 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6008Ok() (*string, bool) {
	if o == nil || o.Var6008 == nil {
		return nil, false
	}
	return o.Var6008, true
}

// HasVar6008 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6008() bool {
	if o != nil && o.Var6008 != nil {
		return true
	}

	return false
}

// SetVar6008 gets a reference to the given string and assigns it to the Var6008 field.
func (o *InlineResponse20017) SetVar6008(v string) {
	o.Var6008 = &v
}

// GetVar6070 returns the Var6070 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6070() string {
	if o == nil || o.Var6070 == nil {
		var ret string
		return ret
	}
	return *o.Var6070
}

// GetVar6070Ok returns a tuple with the Var6070 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6070Ok() (*string, bool) {
	if o == nil || o.Var6070 == nil {
		return nil, false
	}
	return o.Var6070, true
}

// HasVar6070 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6070() bool {
	if o != nil && o.Var6070 != nil {
		return true
	}

	return false
}

// SetVar6070 gets a reference to the given string and assigns it to the Var6070 field.
func (o *InlineResponse20017) SetVar6070(v string) {
	o.Var6070 = &v
}

// GetVar6072 returns the Var6072 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6072() string {
	if o == nil || o.Var6072 == nil {
		var ret string
		return ret
	}
	return *o.Var6072
}

// GetVar6072Ok returns a tuple with the Var6072 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6072Ok() (*string, bool) {
	if o == nil || o.Var6072 == nil {
		return nil, false
	}
	return o.Var6072, true
}

// HasVar6072 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6072() bool {
	if o != nil && o.Var6072 != nil {
		return true
	}

	return false
}

// SetVar6072 gets a reference to the given string and assigns it to the Var6072 field.
func (o *InlineResponse20017) SetVar6072(v string) {
	o.Var6072 = &v
}

// GetVar6073 returns the Var6073 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6073() string {
	if o == nil || o.Var6073 == nil {
		var ret string
		return ret
	}
	return *o.Var6073
}

// GetVar6073Ok returns a tuple with the Var6073 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6073Ok() (*string, bool) {
	if o == nil || o.Var6073 == nil {
		return nil, false
	}
	return o.Var6073, true
}

// HasVar6073 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6073() bool {
	if o != nil && o.Var6073 != nil {
		return true
	}

	return false
}

// SetVar6073 gets a reference to the given string and assigns it to the Var6073 field.
func (o *InlineResponse20017) SetVar6073(v string) {
	o.Var6073 = &v
}

// GetVar6119 returns the Var6119 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6119() string {
	if o == nil || o.Var6119 == nil {
		var ret string
		return ret
	}
	return *o.Var6119
}

// GetVar6119Ok returns a tuple with the Var6119 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6119Ok() (*string, bool) {
	if o == nil || o.Var6119 == nil {
		return nil, false
	}
	return o.Var6119, true
}

// HasVar6119 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6119() bool {
	if o != nil && o.Var6119 != nil {
		return true
	}

	return false
}

// SetVar6119 gets a reference to the given string and assigns it to the Var6119 field.
func (o *InlineResponse20017) SetVar6119(v string) {
	o.Var6119 = &v
}

// GetVar6457 returns the Var6457 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6457() string {
	if o == nil || o.Var6457 == nil {
		var ret string
		return ret
	}
	return *o.Var6457
}

// GetVar6457Ok returns a tuple with the Var6457 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6457Ok() (*string, bool) {
	if o == nil || o.Var6457 == nil {
		return nil, false
	}
	return o.Var6457, true
}

// HasVar6457 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6457() bool {
	if o != nil && o.Var6457 != nil {
		return true
	}

	return false
}

// SetVar6457 gets a reference to the given string and assigns it to the Var6457 field.
func (o *InlineResponse20017) SetVar6457(v string) {
	o.Var6457 = &v
}

// GetVar6509 returns the Var6509 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar6509() string {
	if o == nil || o.Var6509 == nil {
		var ret string
		return ret
	}
	return *o.Var6509
}

// GetVar6509Ok returns a tuple with the Var6509 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar6509Ok() (*string, bool) {
	if o == nil || o.Var6509 == nil {
		return nil, false
	}
	return o.Var6509, true
}

// HasVar6509 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar6509() bool {
	if o != nil && o.Var6509 != nil {
		return true
	}

	return false
}

// SetVar6509 gets a reference to the given string and assigns it to the Var6509 field.
func (o *InlineResponse20017) SetVar6509(v string) {
	o.Var6509 = &v
}

// GetVar7051 returns the Var7051 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7051() string {
	if o == nil || o.Var7051 == nil {
		var ret string
		return ret
	}
	return *o.Var7051
}

// GetVar7051Ok returns a tuple with the Var7051 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7051Ok() (*string, bool) {
	if o == nil || o.Var7051 == nil {
		return nil, false
	}
	return o.Var7051, true
}

// HasVar7051 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7051() bool {
	if o != nil && o.Var7051 != nil {
		return true
	}

	return false
}

// SetVar7051 gets a reference to the given string and assigns it to the Var7051 field.
func (o *InlineResponse20017) SetVar7051(v string) {
	o.Var7051 = &v
}

// GetVar7094 returns the Var7094 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7094() string {
	if o == nil || o.Var7094 == nil {
		var ret string
		return ret
	}
	return *o.Var7094
}

// GetVar7094Ok returns a tuple with the Var7094 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7094Ok() (*string, bool) {
	if o == nil || o.Var7094 == nil {
		return nil, false
	}
	return o.Var7094, true
}

// HasVar7094 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7094() bool {
	if o != nil && o.Var7094 != nil {
		return true
	}

	return false
}

// SetVar7094 gets a reference to the given string and assigns it to the Var7094 field.
func (o *InlineResponse20017) SetVar7094(v string) {
	o.Var7094 = &v
}

// GetVar7219 returns the Var7219 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7219() string {
	if o == nil || o.Var7219 == nil {
		var ret string
		return ret
	}
	return *o.Var7219
}

// GetVar7219Ok returns a tuple with the Var7219 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7219Ok() (*string, bool) {
	if o == nil || o.Var7219 == nil {
		return nil, false
	}
	return o.Var7219, true
}

// HasVar7219 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7219() bool {
	if o != nil && o.Var7219 != nil {
		return true
	}

	return false
}

// SetVar7219 gets a reference to the given string and assigns it to the Var7219 field.
func (o *InlineResponse20017) SetVar7219(v string) {
	o.Var7219 = &v
}

// GetVar7220 returns the Var7220 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7220() string {
	if o == nil || o.Var7220 == nil {
		var ret string
		return ret
	}
	return *o.Var7220
}

// GetVar7220Ok returns a tuple with the Var7220 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7220Ok() (*string, bool) {
	if o == nil || o.Var7220 == nil {
		return nil, false
	}
	return o.Var7220, true
}

// HasVar7220 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7220() bool {
	if o != nil && o.Var7220 != nil {
		return true
	}

	return false
}

// SetVar7220 gets a reference to the given string and assigns it to the Var7220 field.
func (o *InlineResponse20017) SetVar7220(v string) {
	o.Var7220 = &v
}

// GetVar7221 returns the Var7221 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7221() string {
	if o == nil || o.Var7221 == nil {
		var ret string
		return ret
	}
	return *o.Var7221
}

// GetVar7221Ok returns a tuple with the Var7221 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7221Ok() (*string, bool) {
	if o == nil || o.Var7221 == nil {
		return nil, false
	}
	return o.Var7221, true
}

// HasVar7221 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7221() bool {
	if o != nil && o.Var7221 != nil {
		return true
	}

	return false
}

// SetVar7221 gets a reference to the given string and assigns it to the Var7221 field.
func (o *InlineResponse20017) SetVar7221(v string) {
	o.Var7221 = &v
}

// GetVar7280 returns the Var7280 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7280() string {
	if o == nil || o.Var7280 == nil {
		var ret string
		return ret
	}
	return *o.Var7280
}

// GetVar7280Ok returns a tuple with the Var7280 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7280Ok() (*string, bool) {
	if o == nil || o.Var7280 == nil {
		return nil, false
	}
	return o.Var7280, true
}

// HasVar7280 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7280() bool {
	if o != nil && o.Var7280 != nil {
		return true
	}

	return false
}

// SetVar7280 gets a reference to the given string and assigns it to the Var7280 field.
func (o *InlineResponse20017) SetVar7280(v string) {
	o.Var7280 = &v
}

// GetVar7281 returns the Var7281 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7281() string {
	if o == nil || o.Var7281 == nil {
		var ret string
		return ret
	}
	return *o.Var7281
}

// GetVar7281Ok returns a tuple with the Var7281 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7281Ok() (*string, bool) {
	if o == nil || o.Var7281 == nil {
		return nil, false
	}
	return o.Var7281, true
}

// HasVar7281 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7281() bool {
	if o != nil && o.Var7281 != nil {
		return true
	}

	return false
}

// SetVar7281 gets a reference to the given string and assigns it to the Var7281 field.
func (o *InlineResponse20017) SetVar7281(v string) {
	o.Var7281 = &v
}

// GetVar7282 returns the Var7282 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7282() string {
	if o == nil || o.Var7282 == nil {
		var ret string
		return ret
	}
	return *o.Var7282
}

// GetVar7282Ok returns a tuple with the Var7282 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7282Ok() (*string, bool) {
	if o == nil || o.Var7282 == nil {
		return nil, false
	}
	return o.Var7282, true
}

// HasVar7282 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7282() bool {
	if o != nil && o.Var7282 != nil {
		return true
	}

	return false
}

// SetVar7282 gets a reference to the given string and assigns it to the Var7282 field.
func (o *InlineResponse20017) SetVar7282(v string) {
	o.Var7282 = &v
}

// GetVar7633 returns the Var7633 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7633() string {
	if o == nil || o.Var7633 == nil {
		var ret string
		return ret
	}
	return *o.Var7633
}

// GetVar7633Ok returns a tuple with the Var7633 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7633Ok() (*string, bool) {
	if o == nil || o.Var7633 == nil {
		return nil, false
	}
	return o.Var7633, true
}

// HasVar7633 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7633() bool {
	if o != nil && o.Var7633 != nil {
		return true
	}

	return false
}

// SetVar7633 gets a reference to the given string and assigns it to the Var7633 field.
func (o *InlineResponse20017) SetVar7633(v string) {
	o.Var7633 = &v
}

// GetVar7284 returns the Var7284 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7284() string {
	if o == nil || o.Var7284 == nil {
		var ret string
		return ret
	}
	return *o.Var7284
}

// GetVar7284Ok returns a tuple with the Var7284 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7284Ok() (*string, bool) {
	if o == nil || o.Var7284 == nil {
		return nil, false
	}
	return o.Var7284, true
}

// HasVar7284 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7284() bool {
	if o != nil && o.Var7284 != nil {
		return true
	}

	return false
}

// SetVar7284 gets a reference to the given string and assigns it to the Var7284 field.
func (o *InlineResponse20017) SetVar7284(v string) {
	o.Var7284 = &v
}

// GetVar7285 returns the Var7285 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7285() string {
	if o == nil || o.Var7285 == nil {
		var ret string
		return ret
	}
	return *o.Var7285
}

// GetVar7285Ok returns a tuple with the Var7285 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7285Ok() (*string, bool) {
	if o == nil || o.Var7285 == nil {
		return nil, false
	}
	return o.Var7285, true
}

// HasVar7285 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7285() bool {
	if o != nil && o.Var7285 != nil {
		return true
	}

	return false
}

// SetVar7285 gets a reference to the given string and assigns it to the Var7285 field.
func (o *InlineResponse20017) SetVar7285(v string) {
	o.Var7285 = &v
}

// GetVar7286 returns the Var7286 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7286() string {
	if o == nil || o.Var7286 == nil {
		var ret string
		return ret
	}
	return *o.Var7286
}

// GetVar7286Ok returns a tuple with the Var7286 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7286Ok() (*string, bool) {
	if o == nil || o.Var7286 == nil {
		return nil, false
	}
	return o.Var7286, true
}

// HasVar7286 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7286() bool {
	if o != nil && o.Var7286 != nil {
		return true
	}

	return false
}

// SetVar7286 gets a reference to the given string and assigns it to the Var7286 field.
func (o *InlineResponse20017) SetVar7286(v string) {
	o.Var7286 = &v
}

// GetVar7287 returns the Var7287 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7287() string {
	if o == nil || o.Var7287 == nil {
		var ret string
		return ret
	}
	return *o.Var7287
}

// GetVar7287Ok returns a tuple with the Var7287 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7287Ok() (*string, bool) {
	if o == nil || o.Var7287 == nil {
		return nil, false
	}
	return o.Var7287, true
}

// HasVar7287 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7287() bool {
	if o != nil && o.Var7287 != nil {
		return true
	}

	return false
}

// SetVar7287 gets a reference to the given string and assigns it to the Var7287 field.
func (o *InlineResponse20017) SetVar7287(v string) {
	o.Var7287 = &v
}

// GetVar7288 returns the Var7288 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7288() string {
	if o == nil || o.Var7288 == nil {
		var ret string
		return ret
	}
	return *o.Var7288
}

// GetVar7288Ok returns a tuple with the Var7288 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7288Ok() (*string, bool) {
	if o == nil || o.Var7288 == nil {
		return nil, false
	}
	return o.Var7288, true
}

// HasVar7288 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7288() bool {
	if o != nil && o.Var7288 != nil {
		return true
	}

	return false
}

// SetVar7288 gets a reference to the given string and assigns it to the Var7288 field.
func (o *InlineResponse20017) SetVar7288(v string) {
	o.Var7288 = &v
}

// GetVar7289 returns the Var7289 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7289() string {
	if o == nil || o.Var7289 == nil {
		var ret string
		return ret
	}
	return *o.Var7289
}

// GetVar7289Ok returns a tuple with the Var7289 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7289Ok() (*string, bool) {
	if o == nil || o.Var7289 == nil {
		return nil, false
	}
	return o.Var7289, true
}

// HasVar7289 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7289() bool {
	if o != nil && o.Var7289 != nil {
		return true
	}

	return false
}

// SetVar7289 gets a reference to the given string and assigns it to the Var7289 field.
func (o *InlineResponse20017) SetVar7289(v string) {
	o.Var7289 = &v
}

// GetVar7290 returns the Var7290 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7290() string {
	if o == nil || o.Var7290 == nil {
		var ret string
		return ret
	}
	return *o.Var7290
}

// GetVar7290Ok returns a tuple with the Var7290 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7290Ok() (*string, bool) {
	if o == nil || o.Var7290 == nil {
		return nil, false
	}
	return o.Var7290, true
}

// HasVar7290 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7290() bool {
	if o != nil && o.Var7290 != nil {
		return true
	}

	return false
}

// SetVar7290 gets a reference to the given string and assigns it to the Var7290 field.
func (o *InlineResponse20017) SetVar7290(v string) {
	o.Var7290 = &v
}

// GetVar7291 returns the Var7291 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7291() string {
	if o == nil || o.Var7291 == nil {
		var ret string
		return ret
	}
	return *o.Var7291
}

// GetVar7291Ok returns a tuple with the Var7291 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7291Ok() (*string, bool) {
	if o == nil || o.Var7291 == nil {
		return nil, false
	}
	return o.Var7291, true
}

// HasVar7291 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7291() bool {
	if o != nil && o.Var7291 != nil {
		return true
	}

	return false
}

// SetVar7291 gets a reference to the given string and assigns it to the Var7291 field.
func (o *InlineResponse20017) SetVar7291(v string) {
	o.Var7291 = &v
}

// GetVar7292 returns the Var7292 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7292() string {
	if o == nil || o.Var7292 == nil {
		var ret string
		return ret
	}
	return *o.Var7292
}

// GetVar7292Ok returns a tuple with the Var7292 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7292Ok() (*string, bool) {
	if o == nil || o.Var7292 == nil {
		return nil, false
	}
	return o.Var7292, true
}

// HasVar7292 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7292() bool {
	if o != nil && o.Var7292 != nil {
		return true
	}

	return false
}

// SetVar7292 gets a reference to the given string and assigns it to the Var7292 field.
func (o *InlineResponse20017) SetVar7292(v string) {
	o.Var7292 = &v
}

// GetVar7293 returns the Var7293 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7293() string {
	if o == nil || o.Var7293 == nil {
		var ret string
		return ret
	}
	return *o.Var7293
}

// GetVar7293Ok returns a tuple with the Var7293 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7293Ok() (*string, bool) {
	if o == nil || o.Var7293 == nil {
		return nil, false
	}
	return o.Var7293, true
}

// HasVar7293 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7293() bool {
	if o != nil && o.Var7293 != nil {
		return true
	}

	return false
}

// SetVar7293 gets a reference to the given string and assigns it to the Var7293 field.
func (o *InlineResponse20017) SetVar7293(v string) {
	o.Var7293 = &v
}

// GetVar7294 returns the Var7294 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7294() string {
	if o == nil || o.Var7294 == nil {
		var ret string
		return ret
	}
	return *o.Var7294
}

// GetVar7294Ok returns a tuple with the Var7294 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7294Ok() (*string, bool) {
	if o == nil || o.Var7294 == nil {
		return nil, false
	}
	return o.Var7294, true
}

// HasVar7294 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7294() bool {
	if o != nil && o.Var7294 != nil {
		return true
	}

	return false
}

// SetVar7294 gets a reference to the given string and assigns it to the Var7294 field.
func (o *InlineResponse20017) SetVar7294(v string) {
	o.Var7294 = &v
}

// GetVar7295 returns the Var7295 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7295() string {
	if o == nil || o.Var7295 == nil {
		var ret string
		return ret
	}
	return *o.Var7295
}

// GetVar7295Ok returns a tuple with the Var7295 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7295Ok() (*string, bool) {
	if o == nil || o.Var7295 == nil {
		return nil, false
	}
	return o.Var7295, true
}

// HasVar7295 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7295() bool {
	if o != nil && o.Var7295 != nil {
		return true
	}

	return false
}

// SetVar7295 gets a reference to the given string and assigns it to the Var7295 field.
func (o *InlineResponse20017) SetVar7295(v string) {
	o.Var7295 = &v
}

// GetVar7296 returns the Var7296 field value if set, zero value otherwise.
func (o *InlineResponse20017) GetVar7296() string {
	if o == nil || o.Var7296 == nil {
		var ret string
		return ret
	}
	return *o.Var7296
}

// GetVar7296Ok returns a tuple with the Var7296 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20017) GetVar7296Ok() (*string, bool) {
	if o == nil || o.Var7296 == nil {
		return nil, false
	}
	return o.Var7296, true
}

// HasVar7296 returns a boolean if a field has been set.
func (o *InlineResponse20017) HasVar7296() bool {
	if o != nil && o.Var7296 != nil {
		return true
	}

	return false
}

// SetVar7296 gets a reference to the given string and assigns it to the Var7296 field.
func (o *InlineResponse20017) SetVar7296(v string) {
	o.Var7296 = &v
}

func (o InlineResponse20017) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ServerId != nil {
		toSerialize["server_id"] = o.ServerId
	}
	if o.Conid != nil {
		toSerialize["conid"] = o.Conid
	}
	if o.Updated != nil {
		toSerialize["_updated"] = o.Updated
	}
	if o.Var31 != nil {
		toSerialize["31"] = o.Var31
	}
	if o.Var55 != nil {
		toSerialize["55"] = o.Var55
	}
	if o.Var58 != nil {
		toSerialize["58"] = o.Var58
	}
	if o.Var70 != nil {
		toSerialize["70"] = o.Var70
	}
	if o.Var71 != nil {
		toSerialize["71"] = o.Var71
	}
	if o.Var72 != nil {
		toSerialize["72"] = o.Var72
	}
	if o.Var73 != nil {
		toSerialize["73"] = o.Var73
	}
	if o.Var74 != nil {
		toSerialize["74"] = o.Var74
	}
	if o.Var75 != nil {
		toSerialize["75"] = o.Var75
	}
	if o.Var76 != nil {
		toSerialize["76"] = o.Var76
	}
	if o.Var77 != nil {
		toSerialize["77"] = o.Var77
	}
	if o.Var78 != nil {
		toSerialize["78"] = o.Var78
	}
	if o.Var82 != nil {
		toSerialize["82"] = o.Var82
	}
	if o.Var83 != nil {
		toSerialize["83"] = o.Var83
	}
	if o.Var84 != nil {
		toSerialize["84"] = o.Var84
	}
	if o.Var85 != nil {
		toSerialize["85"] = o.Var85
	}
	if o.Var86 != nil {
		toSerialize["86"] = o.Var86
	}
	if o.Var87 != nil {
		toSerialize["87"] = o.Var87
	}
	if o.Var88 != nil {
		toSerialize["88"] = o.Var88
	}
	if o.Var6004 != nil {
		toSerialize["6004"] = o.Var6004
	}
	if o.Var6008 != nil {
		toSerialize["6008"] = o.Var6008
	}
	if o.Var6070 != nil {
		toSerialize["6070"] = o.Var6070
	}
	if o.Var6072 != nil {
		toSerialize["6072"] = o.Var6072
	}
	if o.Var6073 != nil {
		toSerialize["6073"] = o.Var6073
	}
	if o.Var6119 != nil {
		toSerialize["6119"] = o.Var6119
	}
	if o.Var6457 != nil {
		toSerialize["6457"] = o.Var6457
	}
	if o.Var6509 != nil {
		toSerialize["6509"] = o.Var6509
	}
	if o.Var7051 != nil {
		toSerialize["7051"] = o.Var7051
	}
	if o.Var7094 != nil {
		toSerialize["7094"] = o.Var7094
	}
	if o.Var7219 != nil {
		toSerialize["7219"] = o.Var7219
	}
	if o.Var7220 != nil {
		toSerialize["7220"] = o.Var7220
	}
	if o.Var7221 != nil {
		toSerialize["7221"] = o.Var7221
	}
	if o.Var7280 != nil {
		toSerialize["7280"] = o.Var7280
	}
	if o.Var7281 != nil {
		toSerialize["7281"] = o.Var7281
	}
	if o.Var7282 != nil {
		toSerialize["7282"] = o.Var7282
	}
	if o.Var7633 != nil {
		toSerialize["7633"] = o.Var7633
	}
	if o.Var7284 != nil {
		toSerialize["7284"] = o.Var7284
	}
	if o.Var7285 != nil {
		toSerialize["7285"] = o.Var7285
	}
	if o.Var7286 != nil {
		toSerialize["7286"] = o.Var7286
	}
	if o.Var7287 != nil {
		toSerialize["7287"] = o.Var7287
	}
	if o.Var7288 != nil {
		toSerialize["7288"] = o.Var7288
	}
	if o.Var7289 != nil {
		toSerialize["7289"] = o.Var7289
	}
	if o.Var7290 != nil {
		toSerialize["7290"] = o.Var7290
	}
	if o.Var7291 != nil {
		toSerialize["7291"] = o.Var7291
	}
	if o.Var7292 != nil {
		toSerialize["7292"] = o.Var7292
	}
	if o.Var7293 != nil {
		toSerialize["7293"] = o.Var7293
	}
	if o.Var7294 != nil {
		toSerialize["7294"] = o.Var7294
	}
	if o.Var7295 != nil {
		toSerialize["7295"] = o.Var7295
	}
	if o.Var7296 != nil {
		toSerialize["7296"] = o.Var7296
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20017 struct {
	value *InlineResponse20017
	isSet bool
}

func (v NullableInlineResponse20017) Get() *InlineResponse20017 {
	return v.value
}

func (v *NullableInlineResponse20017) Set(val *InlineResponse20017) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20017) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20017) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20017(val *InlineResponse20017) *NullableInlineResponse20017 {
	return &NullableInlineResponse20017{value: val, isSet: true}
}

func (v NullableInlineResponse20017) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20017) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


