/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20020Locations struct for InlineResponse20020Locations
type InlineResponse20020Locations struct {
	DisplayName *string `json:"display_name,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewInlineResponse20020Locations instantiates a new InlineResponse20020Locations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20020Locations() *InlineResponse20020Locations {
	this := InlineResponse20020Locations{}
	return &this
}

// NewInlineResponse20020LocationsWithDefaults instantiates a new InlineResponse20020Locations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20020LocationsWithDefaults() *InlineResponse20020Locations {
	this := InlineResponse20020Locations{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *InlineResponse20020Locations) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20020Locations) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *InlineResponse20020Locations) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *InlineResponse20020Locations) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InlineResponse20020Locations) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20020Locations) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InlineResponse20020Locations) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InlineResponse20020Locations) SetType(v string) {
	o.Type = &v
}

func (o InlineResponse20020Locations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DisplayName != nil {
		toSerialize["display_name"] = o.DisplayName
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20020Locations struct {
	value *InlineResponse20020Locations
	isSet bool
}

func (v NullableInlineResponse20020Locations) Get() *InlineResponse20020Locations {
	return v.value
}

func (v *NullableInlineResponse20020Locations) Set(val *InlineResponse20020Locations) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20020Locations) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20020Locations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20020Locations(val *InlineResponse20020Locations) *NullableInlineResponse20020Locations {
	return &NullableInlineResponse20020Locations{value: val, isSet: true}
}

func (v NullableInlineResponse20020Locations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20020Locations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


