/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse20015 struct for InlineResponse20015
type InlineResponse20015 struct {
	Amount *InlineResponse20015Amount `json:"amount,omitempty"`
	Equity *InlineResponse20015Equity `json:"equity,omitempty"`
	Initial *InlineResponse20015Equity `json:"initial,omitempty"`
	Maintenance *InlineResponse20015Equity `json:"maintenance,omitempty"`
	Warn *string `json:"warn,omitempty"`
	Error *string `json:"error,omitempty"`
}

// NewInlineResponse20015 instantiates a new InlineResponse20015 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse20015() *InlineResponse20015 {
	this := InlineResponse20015{}
	return &this
}

// NewInlineResponse20015WithDefaults instantiates a new InlineResponse20015 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse20015WithDefaults() *InlineResponse20015 {
	this := InlineResponse20015{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *InlineResponse20015) GetAmount() InlineResponse20015Amount {
	if o == nil || o.Amount == nil {
		var ret InlineResponse20015Amount
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetAmountOk() (*InlineResponse20015Amount, bool) {
	if o == nil || o.Amount == nil {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *InlineResponse20015) HasAmount() bool {
	if o != nil && o.Amount != nil {
		return true
	}

	return false
}

// SetAmount gets a reference to the given InlineResponse20015Amount and assigns it to the Amount field.
func (o *InlineResponse20015) SetAmount(v InlineResponse20015Amount) {
	o.Amount = &v
}

// GetEquity returns the Equity field value if set, zero value otherwise.
func (o *InlineResponse20015) GetEquity() InlineResponse20015Equity {
	if o == nil || o.Equity == nil {
		var ret InlineResponse20015Equity
		return ret
	}
	return *o.Equity
}

// GetEquityOk returns a tuple with the Equity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetEquityOk() (*InlineResponse20015Equity, bool) {
	if o == nil || o.Equity == nil {
		return nil, false
	}
	return o.Equity, true
}

// HasEquity returns a boolean if a field has been set.
func (o *InlineResponse20015) HasEquity() bool {
	if o != nil && o.Equity != nil {
		return true
	}

	return false
}

// SetEquity gets a reference to the given InlineResponse20015Equity and assigns it to the Equity field.
func (o *InlineResponse20015) SetEquity(v InlineResponse20015Equity) {
	o.Equity = &v
}

// GetInitial returns the Initial field value if set, zero value otherwise.
func (o *InlineResponse20015) GetInitial() InlineResponse20015Equity {
	if o == nil || o.Initial == nil {
		var ret InlineResponse20015Equity
		return ret
	}
	return *o.Initial
}

// GetInitialOk returns a tuple with the Initial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetInitialOk() (*InlineResponse20015Equity, bool) {
	if o == nil || o.Initial == nil {
		return nil, false
	}
	return o.Initial, true
}

// HasInitial returns a boolean if a field has been set.
func (o *InlineResponse20015) HasInitial() bool {
	if o != nil && o.Initial != nil {
		return true
	}

	return false
}

// SetInitial gets a reference to the given InlineResponse20015Equity and assigns it to the Initial field.
func (o *InlineResponse20015) SetInitial(v InlineResponse20015Equity) {
	o.Initial = &v
}

// GetMaintenance returns the Maintenance field value if set, zero value otherwise.
func (o *InlineResponse20015) GetMaintenance() InlineResponse20015Equity {
	if o == nil || o.Maintenance == nil {
		var ret InlineResponse20015Equity
		return ret
	}
	return *o.Maintenance
}

// GetMaintenanceOk returns a tuple with the Maintenance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetMaintenanceOk() (*InlineResponse20015Equity, bool) {
	if o == nil || o.Maintenance == nil {
		return nil, false
	}
	return o.Maintenance, true
}

// HasMaintenance returns a boolean if a field has been set.
func (o *InlineResponse20015) HasMaintenance() bool {
	if o != nil && o.Maintenance != nil {
		return true
	}

	return false
}

// SetMaintenance gets a reference to the given InlineResponse20015Equity and assigns it to the Maintenance field.
func (o *InlineResponse20015) SetMaintenance(v InlineResponse20015Equity) {
	o.Maintenance = &v
}

// GetWarn returns the Warn field value if set, zero value otherwise.
func (o *InlineResponse20015) GetWarn() string {
	if o == nil || o.Warn == nil {
		var ret string
		return ret
	}
	return *o.Warn
}

// GetWarnOk returns a tuple with the Warn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetWarnOk() (*string, bool) {
	if o == nil || o.Warn == nil {
		return nil, false
	}
	return o.Warn, true
}

// HasWarn returns a boolean if a field has been set.
func (o *InlineResponse20015) HasWarn() bool {
	if o != nil && o.Warn != nil {
		return true
	}

	return false
}

// SetWarn gets a reference to the given string and assigns it to the Warn field.
func (o *InlineResponse20015) SetWarn(v string) {
	o.Warn = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *InlineResponse20015) GetError() string {
	if o == nil || o.Error == nil {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse20015) GetErrorOk() (*string, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *InlineResponse20015) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *InlineResponse20015) SetError(v string) {
	o.Error = &v
}

func (o InlineResponse20015) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Amount != nil {
		toSerialize["amount"] = o.Amount
	}
	if o.Equity != nil {
		toSerialize["equity"] = o.Equity
	}
	if o.Initial != nil {
		toSerialize["initial"] = o.Initial
	}
	if o.Maintenance != nil {
		toSerialize["maintenance"] = o.Maintenance
	}
	if o.Warn != nil {
		toSerialize["warn"] = o.Warn
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse20015 struct {
	value *InlineResponse20015
	isSet bool
}

func (v NullableInlineResponse20015) Get() *InlineResponse20015 {
	return v.value
}

func (v *NullableInlineResponse20015) Set(val *InlineResponse20015) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse20015) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse20015) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse20015(val *InlineResponse20015) *NullableInlineResponse20015 {
	return &NullableInlineResponse20015{value: val, isSet: true}
}

func (v NullableInlineResponse20015) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse20015) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


