/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// SecdefInfo Contains some basic info of contract
type SecdefInfo struct {
	Conid *float32 `json:"conid,omitempty"`
	SecType *string `json:"secType,omitempty"`
	Exchange *string `json:"exchange,omitempty"`
	// for exmple FB
	Symbol *string `json:"symbol,omitempty"`
	Desc1 *string `json:"desc1,omitempty"`
	Desc2 *string `json:"desc2,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Strike *string `json:"strike,omitempty"`
	Right *string `json:"right,omitempty"`
	TradingClass *string `json:"tradingClass,omitempty"`
	ListingExchange *string `json:"listingExchange,omitempty"`
	ValidExchanges *string `json:"validExchanges,omitempty"`
}

// NewSecdefInfo instantiates a new SecdefInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecdefInfo() *SecdefInfo {
	this := SecdefInfo{}
	return &this
}

// NewSecdefInfoWithDefaults instantiates a new SecdefInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecdefInfoWithDefaults() *SecdefInfo {
	this := SecdefInfo{}
	return &this
}

// GetConid returns the Conid field value if set, zero value otherwise.
func (o *SecdefInfo) GetConid() float32 {
	if o == nil || o.Conid == nil {
		var ret float32
		return ret
	}
	return *o.Conid
}

// GetConidOk returns a tuple with the Conid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetConidOk() (*float32, bool) {
	if o == nil || o.Conid == nil {
		return nil, false
	}
	return o.Conid, true
}

// HasConid returns a boolean if a field has been set.
func (o *SecdefInfo) HasConid() bool {
	if o != nil && o.Conid != nil {
		return true
	}

	return false
}

// SetConid gets a reference to the given float32 and assigns it to the Conid field.
func (o *SecdefInfo) SetConid(v float32) {
	o.Conid = &v
}

// GetSecType returns the SecType field value if set, zero value otherwise.
func (o *SecdefInfo) GetSecType() string {
	if o == nil || o.SecType == nil {
		var ret string
		return ret
	}
	return *o.SecType
}

// GetSecTypeOk returns a tuple with the SecType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetSecTypeOk() (*string, bool) {
	if o == nil || o.SecType == nil {
		return nil, false
	}
	return o.SecType, true
}

// HasSecType returns a boolean if a field has been set.
func (o *SecdefInfo) HasSecType() bool {
	if o != nil && o.SecType != nil {
		return true
	}

	return false
}

// SetSecType gets a reference to the given string and assigns it to the SecType field.
func (o *SecdefInfo) SetSecType(v string) {
	o.SecType = &v
}

// GetExchange returns the Exchange field value if set, zero value otherwise.
func (o *SecdefInfo) GetExchange() string {
	if o == nil || o.Exchange == nil {
		var ret string
		return ret
	}
	return *o.Exchange
}

// GetExchangeOk returns a tuple with the Exchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetExchangeOk() (*string, bool) {
	if o == nil || o.Exchange == nil {
		return nil, false
	}
	return o.Exchange, true
}

// HasExchange returns a boolean if a field has been set.
func (o *SecdefInfo) HasExchange() bool {
	if o != nil && o.Exchange != nil {
		return true
	}

	return false
}

// SetExchange gets a reference to the given string and assigns it to the Exchange field.
func (o *SecdefInfo) SetExchange(v string) {
	o.Exchange = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *SecdefInfo) GetSymbol() string {
	if o == nil || o.Symbol == nil {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetSymbolOk() (*string, bool) {
	if o == nil || o.Symbol == nil {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *SecdefInfo) HasSymbol() bool {
	if o != nil && o.Symbol != nil {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *SecdefInfo) SetSymbol(v string) {
	o.Symbol = &v
}

// GetDesc1 returns the Desc1 field value if set, zero value otherwise.
func (o *SecdefInfo) GetDesc1() string {
	if o == nil || o.Desc1 == nil {
		var ret string
		return ret
	}
	return *o.Desc1
}

// GetDesc1Ok returns a tuple with the Desc1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetDesc1Ok() (*string, bool) {
	if o == nil || o.Desc1 == nil {
		return nil, false
	}
	return o.Desc1, true
}

// HasDesc1 returns a boolean if a field has been set.
func (o *SecdefInfo) HasDesc1() bool {
	if o != nil && o.Desc1 != nil {
		return true
	}

	return false
}

// SetDesc1 gets a reference to the given string and assigns it to the Desc1 field.
func (o *SecdefInfo) SetDesc1(v string) {
	o.Desc1 = &v
}

// GetDesc2 returns the Desc2 field value if set, zero value otherwise.
func (o *SecdefInfo) GetDesc2() string {
	if o == nil || o.Desc2 == nil {
		var ret string
		return ret
	}
	return *o.Desc2
}

// GetDesc2Ok returns a tuple with the Desc2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetDesc2Ok() (*string, bool) {
	if o == nil || o.Desc2 == nil {
		return nil, false
	}
	return o.Desc2, true
}

// HasDesc2 returns a boolean if a field has been set.
func (o *SecdefInfo) HasDesc2() bool {
	if o != nil && o.Desc2 != nil {
		return true
	}

	return false
}

// SetDesc2 gets a reference to the given string and assigns it to the Desc2 field.
func (o *SecdefInfo) SetDesc2(v string) {
	o.Desc2 = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *SecdefInfo) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *SecdefInfo) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *SecdefInfo) SetCurrency(v string) {
	o.Currency = &v
}

// GetStrike returns the Strike field value if set, zero value otherwise.
func (o *SecdefInfo) GetStrike() string {
	if o == nil || o.Strike == nil {
		var ret string
		return ret
	}
	return *o.Strike
}

// GetStrikeOk returns a tuple with the Strike field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetStrikeOk() (*string, bool) {
	if o == nil || o.Strike == nil {
		return nil, false
	}
	return o.Strike, true
}

// HasStrike returns a boolean if a field has been set.
func (o *SecdefInfo) HasStrike() bool {
	if o != nil && o.Strike != nil {
		return true
	}

	return false
}

// SetStrike gets a reference to the given string and assigns it to the Strike field.
func (o *SecdefInfo) SetStrike(v string) {
	o.Strike = &v
}

// GetRight returns the Right field value if set, zero value otherwise.
func (o *SecdefInfo) GetRight() string {
	if o == nil || o.Right == nil {
		var ret string
		return ret
	}
	return *o.Right
}

// GetRightOk returns a tuple with the Right field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetRightOk() (*string, bool) {
	if o == nil || o.Right == nil {
		return nil, false
	}
	return o.Right, true
}

// HasRight returns a boolean if a field has been set.
func (o *SecdefInfo) HasRight() bool {
	if o != nil && o.Right != nil {
		return true
	}

	return false
}

// SetRight gets a reference to the given string and assigns it to the Right field.
func (o *SecdefInfo) SetRight(v string) {
	o.Right = &v
}

// GetTradingClass returns the TradingClass field value if set, zero value otherwise.
func (o *SecdefInfo) GetTradingClass() string {
	if o == nil || o.TradingClass == nil {
		var ret string
		return ret
	}
	return *o.TradingClass
}

// GetTradingClassOk returns a tuple with the TradingClass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetTradingClassOk() (*string, bool) {
	if o == nil || o.TradingClass == nil {
		return nil, false
	}
	return o.TradingClass, true
}

// HasTradingClass returns a boolean if a field has been set.
func (o *SecdefInfo) HasTradingClass() bool {
	if o != nil && o.TradingClass != nil {
		return true
	}

	return false
}

// SetTradingClass gets a reference to the given string and assigns it to the TradingClass field.
func (o *SecdefInfo) SetTradingClass(v string) {
	o.TradingClass = &v
}

// GetListingExchange returns the ListingExchange field value if set, zero value otherwise.
func (o *SecdefInfo) GetListingExchange() string {
	if o == nil || o.ListingExchange == nil {
		var ret string
		return ret
	}
	return *o.ListingExchange
}

// GetListingExchangeOk returns a tuple with the ListingExchange field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetListingExchangeOk() (*string, bool) {
	if o == nil || o.ListingExchange == nil {
		return nil, false
	}
	return o.ListingExchange, true
}

// HasListingExchange returns a boolean if a field has been set.
func (o *SecdefInfo) HasListingExchange() bool {
	if o != nil && o.ListingExchange != nil {
		return true
	}

	return false
}

// SetListingExchange gets a reference to the given string and assigns it to the ListingExchange field.
func (o *SecdefInfo) SetListingExchange(v string) {
	o.ListingExchange = &v
}

// GetValidExchanges returns the ValidExchanges field value if set, zero value otherwise.
func (o *SecdefInfo) GetValidExchanges() string {
	if o == nil || o.ValidExchanges == nil {
		var ret string
		return ret
	}
	return *o.ValidExchanges
}

// GetValidExchangesOk returns a tuple with the ValidExchanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SecdefInfo) GetValidExchangesOk() (*string, bool) {
	if o == nil || o.ValidExchanges == nil {
		return nil, false
	}
	return o.ValidExchanges, true
}

// HasValidExchanges returns a boolean if a field has been set.
func (o *SecdefInfo) HasValidExchanges() bool {
	if o != nil && o.ValidExchanges != nil {
		return true
	}

	return false
}

// SetValidExchanges gets a reference to the given string and assigns it to the ValidExchanges field.
func (o *SecdefInfo) SetValidExchanges(v string) {
	o.ValidExchanges = &v
}

func (o SecdefInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conid != nil {
		toSerialize["conid"] = o.Conid
	}
	if o.SecType != nil {
		toSerialize["secType"] = o.SecType
	}
	if o.Exchange != nil {
		toSerialize["exchange"] = o.Exchange
	}
	if o.Symbol != nil {
		toSerialize["symbol"] = o.Symbol
	}
	if o.Desc1 != nil {
		toSerialize["desc1"] = o.Desc1
	}
	if o.Desc2 != nil {
		toSerialize["desc2"] = o.Desc2
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.Strike != nil {
		toSerialize["strike"] = o.Strike
	}
	if o.Right != nil {
		toSerialize["right"] = o.Right
	}
	if o.TradingClass != nil {
		toSerialize["tradingClass"] = o.TradingClass
	}
	if o.ListingExchange != nil {
		toSerialize["listingExchange"] = o.ListingExchange
	}
	if o.ValidExchanges != nil {
		toSerialize["validExchanges"] = o.ValidExchanges
	}
	return json.Marshal(toSerialize)
}

type NullableSecdefInfo struct {
	value *SecdefInfo
	isSet bool
}

func (v NullableSecdefInfo) Get() *SecdefInfo {
	return v.value
}

func (v *NullableSecdefInfo) Set(val *SecdefInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableSecdefInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableSecdefInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecdefInfo(val *SecdefInfo) *NullableSecdefInfo {
	return &NullableSecdefInfo{value: val, isSet: true}
}

func (v NullableSecdefInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecdefInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


