/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2001 struct for InlineResponse2001
type InlineResponse2001 struct {
	// optional, if A doesn't exist, it means user can't toggle this option. 0-off, 1-on.
	A *int32 `json:"A,omitempty"`
	// fyi code
	FC *string `json:"FC,omitempty"`
	// disclaimer read, 1 = yes, = 0 no.
	H *int32 `json:"H,omitempty"`
	// detailed description
	FD *string `json:"FD,omitempty"`
	// title
	FN *string `json:"FN,omitempty"`
}

// NewInlineResponse2001 instantiates a new InlineResponse2001 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2001() *InlineResponse2001 {
	this := InlineResponse2001{}
	return &this
}

// NewInlineResponse2001WithDefaults instantiates a new InlineResponse2001 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2001WithDefaults() *InlineResponse2001 {
	this := InlineResponse2001{}
	return &this
}

// GetA returns the A field value if set, zero value otherwise.
func (o *InlineResponse2001) GetA() int32 {
	if o == nil || o.A == nil {
		var ret int32
		return ret
	}
	return *o.A
}

// GetAOk returns a tuple with the A field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001) GetAOk() (*int32, bool) {
	if o == nil || o.A == nil {
		return nil, false
	}
	return o.A, true
}

// HasA returns a boolean if a field has been set.
func (o *InlineResponse2001) HasA() bool {
	if o != nil && o.A != nil {
		return true
	}

	return false
}

// SetA gets a reference to the given int32 and assigns it to the A field.
func (o *InlineResponse2001) SetA(v int32) {
	o.A = &v
}

// GetFC returns the FC field value if set, zero value otherwise.
func (o *InlineResponse2001) GetFC() string {
	if o == nil || o.FC == nil {
		var ret string
		return ret
	}
	return *o.FC
}

// GetFCOk returns a tuple with the FC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001) GetFCOk() (*string, bool) {
	if o == nil || o.FC == nil {
		return nil, false
	}
	return o.FC, true
}

// HasFC returns a boolean if a field has been set.
func (o *InlineResponse2001) HasFC() bool {
	if o != nil && o.FC != nil {
		return true
	}

	return false
}

// SetFC gets a reference to the given string and assigns it to the FC field.
func (o *InlineResponse2001) SetFC(v string) {
	o.FC = &v
}

// GetH returns the H field value if set, zero value otherwise.
func (o *InlineResponse2001) GetH() int32 {
	if o == nil || o.H == nil {
		var ret int32
		return ret
	}
	return *o.H
}

// GetHOk returns a tuple with the H field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001) GetHOk() (*int32, bool) {
	if o == nil || o.H == nil {
		return nil, false
	}
	return o.H, true
}

// HasH returns a boolean if a field has been set.
func (o *InlineResponse2001) HasH() bool {
	if o != nil && o.H != nil {
		return true
	}

	return false
}

// SetH gets a reference to the given int32 and assigns it to the H field.
func (o *InlineResponse2001) SetH(v int32) {
	o.H = &v
}

// GetFD returns the FD field value if set, zero value otherwise.
func (o *InlineResponse2001) GetFD() string {
	if o == nil || o.FD == nil {
		var ret string
		return ret
	}
	return *o.FD
}

// GetFDOk returns a tuple with the FD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001) GetFDOk() (*string, bool) {
	if o == nil || o.FD == nil {
		return nil, false
	}
	return o.FD, true
}

// HasFD returns a boolean if a field has been set.
func (o *InlineResponse2001) HasFD() bool {
	if o != nil && o.FD != nil {
		return true
	}

	return false
}

// SetFD gets a reference to the given string and assigns it to the FD field.
func (o *InlineResponse2001) SetFD(v string) {
	o.FD = &v
}

// GetFN returns the FN field value if set, zero value otherwise.
func (o *InlineResponse2001) GetFN() string {
	if o == nil || o.FN == nil {
		var ret string
		return ret
	}
	return *o.FN
}

// GetFNOk returns a tuple with the FN field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2001) GetFNOk() (*string, bool) {
	if o == nil || o.FN == nil {
		return nil, false
	}
	return o.FN, true
}

// HasFN returns a boolean if a field has been set.
func (o *InlineResponse2001) HasFN() bool {
	if o != nil && o.FN != nil {
		return true
	}

	return false
}

// SetFN gets a reference to the given string and assigns it to the FN field.
func (o *InlineResponse2001) SetFN(v string) {
	o.FN = &v
}

func (o InlineResponse2001) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.A != nil {
		toSerialize["A"] = o.A
	}
	if o.FC != nil {
		toSerialize["FC"] = o.FC
	}
	if o.H != nil {
		toSerialize["H"] = o.H
	}
	if o.FD != nil {
		toSerialize["FD"] = o.FD
	}
	if o.FN != nil {
		toSerialize["FN"] = o.FN
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2001 struct {
	value *InlineResponse2001
	isSet bool
}

func (v NullableInlineResponse2001) Get() *InlineResponse2001 {
	return v.value
}

func (v *NullableInlineResponse2001) Set(val *InlineResponse2001) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2001) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2001) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2001(val *InlineResponse2001) *NullableInlineResponse2001 {
	return &NullableInlineResponse2001{value: val, isSet: true}
}

func (v NullableInlineResponse2001) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2001) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


