/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// Account account information
type Account struct {
	Id *string `json:"id,omitempty"`
	AccountId *string `json:"accountId,omitempty"`
	AccountVan *string `json:"accountVan,omitempty"`
	AccountTitle *string `json:"accountTitle,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	AccountAlias *string `json:"accountAlias,omitempty"`
	AccountStatus *float32 `json:"accountStatus,omitempty"`
	Currency *string `json:"currency,omitempty"`
	Type *string `json:"type,omitempty"`
	TradingType *string `json:"tradingType,omitempty"`
	Faclient *bool `json:"faclient,omitempty"`
	Parent *string `json:"parent,omitempty"`
	Desc *string `json:"desc,omitempty"`
	Covestor *bool `json:"covestor,omitempty"`
	Master *AccountMaster `json:"master,omitempty"`
}

// NewAccount instantiates a new Account object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccount() *Account {
	this := Account{}
	return &this
}

// NewAccountWithDefaults instantiates a new Account object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountWithDefaults() *Account {
	this := Account{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Account) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Account) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Account) SetId(v string) {
	o.Id = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *Account) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *Account) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *Account) SetAccountId(v string) {
	o.AccountId = &v
}

// GetAccountVan returns the AccountVan field value if set, zero value otherwise.
func (o *Account) GetAccountVan() string {
	if o == nil || o.AccountVan == nil {
		var ret string
		return ret
	}
	return *o.AccountVan
}

// GetAccountVanOk returns a tuple with the AccountVan field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountVanOk() (*string, bool) {
	if o == nil || o.AccountVan == nil {
		return nil, false
	}
	return o.AccountVan, true
}

// HasAccountVan returns a boolean if a field has been set.
func (o *Account) HasAccountVan() bool {
	if o != nil && o.AccountVan != nil {
		return true
	}

	return false
}

// SetAccountVan gets a reference to the given string and assigns it to the AccountVan field.
func (o *Account) SetAccountVan(v string) {
	o.AccountVan = &v
}

// GetAccountTitle returns the AccountTitle field value if set, zero value otherwise.
func (o *Account) GetAccountTitle() string {
	if o == nil || o.AccountTitle == nil {
		var ret string
		return ret
	}
	return *o.AccountTitle
}

// GetAccountTitleOk returns a tuple with the AccountTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountTitleOk() (*string, bool) {
	if o == nil || o.AccountTitle == nil {
		return nil, false
	}
	return o.AccountTitle, true
}

// HasAccountTitle returns a boolean if a field has been set.
func (o *Account) HasAccountTitle() bool {
	if o != nil && o.AccountTitle != nil {
		return true
	}

	return false
}

// SetAccountTitle gets a reference to the given string and assigns it to the AccountTitle field.
func (o *Account) SetAccountTitle(v string) {
	o.AccountTitle = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *Account) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *Account) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *Account) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetAccountAlias returns the AccountAlias field value if set, zero value otherwise.
func (o *Account) GetAccountAlias() string {
	if o == nil || o.AccountAlias == nil {
		var ret string
		return ret
	}
	return *o.AccountAlias
}

// GetAccountAliasOk returns a tuple with the AccountAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountAliasOk() (*string, bool) {
	if o == nil || o.AccountAlias == nil {
		return nil, false
	}
	return o.AccountAlias, true
}

// HasAccountAlias returns a boolean if a field has been set.
func (o *Account) HasAccountAlias() bool {
	if o != nil && o.AccountAlias != nil {
		return true
	}

	return false
}

// SetAccountAlias gets a reference to the given string and assigns it to the AccountAlias field.
func (o *Account) SetAccountAlias(v string) {
	o.AccountAlias = &v
}

// GetAccountStatus returns the AccountStatus field value if set, zero value otherwise.
func (o *Account) GetAccountStatus() float32 {
	if o == nil || o.AccountStatus == nil {
		var ret float32
		return ret
	}
	return *o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetAccountStatusOk() (*float32, bool) {
	if o == nil || o.AccountStatus == nil {
		return nil, false
	}
	return o.AccountStatus, true
}

// HasAccountStatus returns a boolean if a field has been set.
func (o *Account) HasAccountStatus() bool {
	if o != nil && o.AccountStatus != nil {
		return true
	}

	return false
}

// SetAccountStatus gets a reference to the given float32 and assigns it to the AccountStatus field.
func (o *Account) SetAccountStatus(v float32) {
	o.AccountStatus = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *Account) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *Account) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *Account) SetCurrency(v string) {
	o.Currency = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *Account) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *Account) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *Account) SetType(v string) {
	o.Type = &v
}

// GetTradingType returns the TradingType field value if set, zero value otherwise.
func (o *Account) GetTradingType() string {
	if o == nil || o.TradingType == nil {
		var ret string
		return ret
	}
	return *o.TradingType
}

// GetTradingTypeOk returns a tuple with the TradingType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetTradingTypeOk() (*string, bool) {
	if o == nil || o.TradingType == nil {
		return nil, false
	}
	return o.TradingType, true
}

// HasTradingType returns a boolean if a field has been set.
func (o *Account) HasTradingType() bool {
	if o != nil && o.TradingType != nil {
		return true
	}

	return false
}

// SetTradingType gets a reference to the given string and assigns it to the TradingType field.
func (o *Account) SetTradingType(v string) {
	o.TradingType = &v
}

// GetFaclient returns the Faclient field value if set, zero value otherwise.
func (o *Account) GetFaclient() bool {
	if o == nil || o.Faclient == nil {
		var ret bool
		return ret
	}
	return *o.Faclient
}

// GetFaclientOk returns a tuple with the Faclient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetFaclientOk() (*bool, bool) {
	if o == nil || o.Faclient == nil {
		return nil, false
	}
	return o.Faclient, true
}

// HasFaclient returns a boolean if a field has been set.
func (o *Account) HasFaclient() bool {
	if o != nil && o.Faclient != nil {
		return true
	}

	return false
}

// SetFaclient gets a reference to the given bool and assigns it to the Faclient field.
func (o *Account) SetFaclient(v bool) {
	o.Faclient = &v
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *Account) GetParent() string {
	if o == nil || o.Parent == nil {
		var ret string
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetParentOk() (*string, bool) {
	if o == nil || o.Parent == nil {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *Account) HasParent() bool {
	if o != nil && o.Parent != nil {
		return true
	}

	return false
}

// SetParent gets a reference to the given string and assigns it to the Parent field.
func (o *Account) SetParent(v string) {
	o.Parent = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *Account) GetDesc() string {
	if o == nil || o.Desc == nil {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetDescOk() (*string, bool) {
	if o == nil || o.Desc == nil {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *Account) HasDesc() bool {
	if o != nil && o.Desc != nil {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *Account) SetDesc(v string) {
	o.Desc = &v
}

// GetCovestor returns the Covestor field value if set, zero value otherwise.
func (o *Account) GetCovestor() bool {
	if o == nil || o.Covestor == nil {
		var ret bool
		return ret
	}
	return *o.Covestor
}

// GetCovestorOk returns a tuple with the Covestor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetCovestorOk() (*bool, bool) {
	if o == nil || o.Covestor == nil {
		return nil, false
	}
	return o.Covestor, true
}

// HasCovestor returns a boolean if a field has been set.
func (o *Account) HasCovestor() bool {
	if o != nil && o.Covestor != nil {
		return true
	}

	return false
}

// SetCovestor gets a reference to the given bool and assigns it to the Covestor field.
func (o *Account) SetCovestor(v bool) {
	o.Covestor = &v
}

// GetMaster returns the Master field value if set, zero value otherwise.
func (o *Account) GetMaster() AccountMaster {
	if o == nil || o.Master == nil {
		var ret AccountMaster
		return ret
	}
	return *o.Master
}

// GetMasterOk returns a tuple with the Master field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Account) GetMasterOk() (*AccountMaster, bool) {
	if o == nil || o.Master == nil {
		return nil, false
	}
	return o.Master, true
}

// HasMaster returns a boolean if a field has been set.
func (o *Account) HasMaster() bool {
	if o != nil && o.Master != nil {
		return true
	}

	return false
}

// SetMaster gets a reference to the given AccountMaster and assigns it to the Master field.
func (o *Account) SetMaster(v AccountMaster) {
	o.Master = &v
}

func (o Account) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.AccountId != nil {
		toSerialize["accountId"] = o.AccountId
	}
	if o.AccountVan != nil {
		toSerialize["accountVan"] = o.AccountVan
	}
	if o.AccountTitle != nil {
		toSerialize["accountTitle"] = o.AccountTitle
	}
	if o.DisplayName != nil {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.AccountAlias != nil {
		toSerialize["accountAlias"] = o.AccountAlias
	}
	if o.AccountStatus != nil {
		toSerialize["accountStatus"] = o.AccountStatus
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.TradingType != nil {
		toSerialize["tradingType"] = o.TradingType
	}
	if o.Faclient != nil {
		toSerialize["faclient"] = o.Faclient
	}
	if o.Parent != nil {
		toSerialize["parent"] = o.Parent
	}
	if o.Desc != nil {
		toSerialize["desc"] = o.Desc
	}
	if o.Covestor != nil {
		toSerialize["covestor"] = o.Covestor
	}
	if o.Master != nil {
		toSerialize["master"] = o.Master
	}
	return json.Marshal(toSerialize)
}

type NullableAccount struct {
	value *Account
	isSet bool
}

func (v NullableAccount) Get() *Account {
	return v.value
}

func (v *NullableAccount) Set(val *Account) {
	v.value = val
	v.isSet = true
}

func (v NullableAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccount(val *Account) *NullableAccount {
	return &NullableAccount{value: val, isSet: true}
}

func (v NullableAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


