/*
 * Client Portal Web API
 *
 * Production version of the Client Portal Web API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineResponse2002 struct for InlineResponse2002
type InlineResponse2002 struct {
	// disclaimer message
	DT *string `json:"DT,omitempty"`
	// fyi code
	FC *string `json:"FC,omitempty"`
}

// NewInlineResponse2002 instantiates a new InlineResponse2002 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse2002() *InlineResponse2002 {
	this := InlineResponse2002{}
	return &this
}

// NewInlineResponse2002WithDefaults instantiates a new InlineResponse2002 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse2002WithDefaults() *InlineResponse2002 {
	this := InlineResponse2002{}
	return &this
}

// GetDT returns the DT field value if set, zero value otherwise.
func (o *InlineResponse2002) GetDT() string {
	if o == nil || o.DT == nil {
		var ret string
		return ret
	}
	return *o.DT
}

// GetDTOk returns a tuple with the DT field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetDTOk() (*string, bool) {
	if o == nil || o.DT == nil {
		return nil, false
	}
	return o.DT, true
}

// HasDT returns a boolean if a field has been set.
func (o *InlineResponse2002) HasDT() bool {
	if o != nil && o.DT != nil {
		return true
	}

	return false
}

// SetDT gets a reference to the given string and assigns it to the DT field.
func (o *InlineResponse2002) SetDT(v string) {
	o.DT = &v
}

// GetFC returns the FC field value if set, zero value otherwise.
func (o *InlineResponse2002) GetFC() string {
	if o == nil || o.FC == nil {
		var ret string
		return ret
	}
	return *o.FC
}

// GetFCOk returns a tuple with the FC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse2002) GetFCOk() (*string, bool) {
	if o == nil || o.FC == nil {
		return nil, false
	}
	return o.FC, true
}

// HasFC returns a boolean if a field has been set.
func (o *InlineResponse2002) HasFC() bool {
	if o != nil && o.FC != nil {
		return true
	}

	return false
}

// SetFC gets a reference to the given string and assigns it to the FC field.
func (o *InlineResponse2002) SetFC(v string) {
	o.FC = &v
}

func (o InlineResponse2002) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DT != nil {
		toSerialize["DT"] = o.DT
	}
	if o.FC != nil {
		toSerialize["FC"] = o.FC
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse2002 struct {
	value *InlineResponse2002
	isSet bool
}

func (v NullableInlineResponse2002) Get() *InlineResponse2002 {
	return v.value
}

func (v *NullableInlineResponse2002) Set(val *InlineResponse2002) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse2002) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse2002) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse2002(val *InlineResponse2002) *NullableInlineResponse2002 {
	return &NullableInlineResponse2002{value: val, isSet: true}
}

func (v NullableInlineResponse2002) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse2002) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


